### ISSUE TITLE
PDF title with spaces seems to lock up the note?

### ISSUE THREAD

**Issue by korm** [elias-sundqvist/obsidian-annotator#10]
When I add something like this to a note's front matter

```
annotation-target: PDF/Some PDF With Spaces In Name.pdf
```

the "Annotate" option does not appear in the three-dot menu, and the note seems to lock up.  I.e., it cannot be edited. 

No doubt this is user error?

**Comment by elias-sundqvist** [comment]
Weird, the situation you describe works for me...
![issue 10 reproduction attempt](https://user-images.githubusercontent.com/9102856/131266085-78226783-5bc7-44dd-a094-86980422b80a.gif)

Do you get any error messages in the terminal? (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>)

**Comment by korm** [comment]
No, messages in the terminal.   If I remove the spaces everything works.

A couple of other things I notice.  If I add annotations, then add a page note, the annotations disappear.   If I delete the page note from the .md view, then then the annotations reappear.  (As they should.).  The page note feature is probably not needed in this implementation.

Also, the markdown view contains a link to this document -- which has nothing to do with the PDF document I am testing.  (Not even a document I've ever accessed at ARXIV.)

https://arxiv.org/pdf/1702.08734.pdf","document":{"title":"1702.08734.pdf","link":[{"href":"urn:x-pdf:45c4698ab25e84725286b0a8e5598cf7"},{"href":"https://arxiv.org/pdf/1702.08734.pdf"}],"documentFingerprint":"45c4698ab25e84725286b0a8e5598cf7"},"target":[{"source":"https://arxiv.org/pdf/1702.08734.pdf","selector":[{"type":"TextPositionSelector","start":1171,"end":1510},{"type":"TextQuoteSelector","exact":"The

**Comment by chinyajie** [comment]
> https://arxiv.org/pdf/1702.08734.pdf","document":{"title":"1702.08734.pdf","link":[{"href":"urn:x-pdf:45c4698ab25e84725286b0a8e5598cf7"},{"href":"https://arxiv.org/pdf/1702.08734.pdf"}],"documentFingerprint":"45c4698ab25e84725286b0a8e5598cf7"},"target":[{"source":"https://arxiv.org/pdf/1702.08734.pdf","selector":[{"type":"TextPositionSelector","start":1171,"end":1510},{"type":"TextQuoteSelector","exact":"The

Same problem to me. Also have this wield link while  all other functions worked well.

**Comment by elias-sundqvist** [comment]
The sample URL is no longer used in the new release. I guess your issue other issues will still be present though. 

I managed to reproduce your page note issue @korm, so I will try to fix that for the next release.

**Comment by GitMurf** [comment]
Oh wow now I know what happened to one of my PDF highlights! haha... I couldn't figure out for the life of me why they were "disappearing" but it was definitely because I was testing the page note on that PDF. So I can confirm I am having the same issue.

**Comment by korm** [comment]
My tests with v0.0.6 indicate the issue "PDF title with spaces..." is probably user error.  I cannot reproduce the error I reported.  IOW, all is working as expected.
