### ISSUE TITLE
drag and drop feature is not working after upgrade obsidian to latest version

### ISSUE THREAD

**Issue by ruanwz** [elias-sundqvist/obsidian-annotator#103]
After obsidian has upgraded to 0.13.14 automatically some days before. I found now I can't use drap and drop function with plugin version 0.1.5.

If I downgrade annotator plugin to 0.1.3, I get the text drag-event::hypothesis-highlight instead of the link.

Could you please check if there is some compatibility issue in the latest obsidian? Thanks!

**Comment by davethehacker** [comment]
I have the same issue with plugin version 0.1.5 and Obsidian v0.13.14

**Comment by 7hx1e** [comment]
same issue here with Annotator 0.1.5 and Obsidian 0.13.19.

**Comment by basekno** [comment]
same issue here with Annotator 0.1.5 and Obsidian 0.13.19.

**Comment by datavistics** [comment]
@elias-sundqvist same issue here with Annotator 0.1.5 and Obsidian 0.13.19.

**Comment by davethehacker** [comment]
> Could this be related to the live mode?

I tried with live mode deactivated and it still didn't work but it may still be related.

**Comment by alexandrephili** [comment]
Same error here : drag-event::hypothesis-highlight
since upgrading to version 0.1.5

Damn, I miss this feature so much!

**Comment by ben1mit** [comment]
same problem. Here is the view from the developer console:

<img width="541" alt="Skjermbilde 2022-01-11 kl  16 28 25" src="https://user-images.githubusercontent.com/48367359/148971686-b2fdb12b-fa3f-4d10-85fb-daf84a89945d.png">

**Comment by ArthurThiam** [comment]
Same issue here! Can temporarily be circumvented by using [["Annotated note" ^ blockID | alias]], if you type some of the text contained in the annotation after "^", Obsidian automatically suggests the relevant block.

**Comment by Torrents-oasis** [comment]
[["Annotated note" ^ blockID | alias]] is not ok. 
Could anyone please show me a demo? 
Thanks a lot.

**Comment by 7hx1e** [comment]
I think it is fixed with the latest update.

**Comment by jasonyanwenl** [comment]
Hi @elias-sundqvist I hit this same issue `drag-event::hypothesis-highlight` again now with Annotator 0.2.10 and Obsidian 1.4.16
Would you mind taking a look when you get a chance? Thank you!
