### ISSUE TITLE
version 0.1.8 no longer shows highlight and annotate

### ISSUE THREAD

**Issue by 7hx1e** [elias-sundqvist/obsidian-annotator#115]
The annotation and highlight no longer show up in the latest version (0.1.8). If I try to highlight a word, the highlighted text does not turn yellow. No visible changes observed and if switch back to MD view, the file is not updated, nothing is appended at the end of the file. Click on the link `show annotation` of previous annotated text also does not take the user to the correct location of the PDF.
The annotate pane is invisible and cannot be enabled.
Tried toggle the setting `Use Annotation Mode By Default`. No visible changes.

**Comment by elias-sundqvist** [comment]
Sounds like hypothes.is fails to load for you. What device are you using? Do you get any error messages in the console?

**Comment by 7hx1e** [comment]
I am on M1 Mac Monterey 12.0.1. Obsidian 0.13.19. No error message in the console.
Uninstall and reinstall the plug-in and Restart Obsidian did not solve the issue.

**Comment by elias-sundqvist** [comment]
Ok, thanks. I'll try to investigste the issue.

**Comment by 7hx1e** [comment]
Sorry, I did not made it clear. No error message pop up but here is a log from the console when developer mode turned on.
[obsidian.md-1642404837803.log](https://github.com/elias-sundqvist/obsidian-annotator/files/7879860/obsidian.md-1642404837803.log)

**Comment by elias-sundqvist** [comment]
The error "WeakRef is not defined" suggests that you are using an obsidian installation with an older version of JavaScript. I think that can be fixed by reinstalling obsidian from the website.

**Comment by 7hx1e** [comment]
Thanks! Reinstall Obsidian solved the problem! I will close the ticket.
