### ISSUE TITLE
Annotations dissapeared from pdf

### ISSUE THREAD

**Issue by HitchRait** [elias-sundqvist/obsidian-annotator#117]
While viewing a note in "Annotate" mode I see "There are no annotations in this group. Create one by selecting some text and clicking the button.", but when i switch to "Open as MD" A see all my previous annotations correctly in edit and in preview mode with proper highlighting. 

Annotator version 0.1.9, Obsidian version 0.13.19

**Comment by elias-sundqvist** [comment]
Did you move the location of the pdf? It's a bit annoying, and I'll try to fix it in the future, but right now the file location is specified both in annotation-taget, and as part of the annotation json. These locations must match. 

If this is the issue for you, you can solve it by creating a new highlight, then doing replace all (ctrl+h) of the "source" location specified of the annotation-json of the old annotations with the source value of the new annotation.

**Comment by HitchRait** [comment]
Oh thanks, that worked! Slight change of folder and it broke all annotations... Hope to see the auto source-update in the future!
