### ISSUE TITLE
Console error when flipping any note (non pdf annotation note) to preview mode

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#13]
This seems to happen the first time I change a note in a pane from edit to preview mode. After I do it once it doesn't seem to happen again when flipping between edit and preview mode until I change to a new note in that pane or restart obsidian at which point it will do it again. Seems to be the "first time" because likely having to do with the markdown preview render actions that happen the first time obsidian renders in preview mode and "caches" much of the file in preview mode.

It seems like it may have to do with block references rendering.

![image](https://user-images.githubusercontent.com/64155612/131281310-e51533f7-6e4a-4f31-81fa-0aae76a3f6ad.png)

**Comment by GitMurf** [comment]
Here is a screen recording showing you how to re-create the error:

https://user-images.githubusercontent.com/64155612/131282251-46778683-3bac-4d74-a507-f583d6512765.mp4

**Comment by GitMurf** [comment]
I am wondering if it has anything to do with this core obsidian setting? I have it set to shortest path so maybe you are looking for a path when it doesn't exist? Just a hunch.

![image](https://user-images.githubusercontent.com/64155612/131282736-7f723a45-f467-49f7-b152-093f32ca197a.png)

**Comment by GitMurf** [comment]
Also looks like if I hover preview over most any link it gives the same error. So again, seems to be when rendering stuff in preview. My thought would be the plugin shouldn't even be doing anything to a file/pane if it isn't marked with `annotation-target:` YAML. Then you can hopefully avoid any issues / conflicts with general Obsidian stuff that isn't in relation to your plugin. Just an idea (easier said than done haha).

**Comment by elias-sundqvist** [comment]
Weird. This doesn't happen for me even though I also use the "shortest path when possible" setting. I'll try to fix it based on your error message though.

**Comment by GitMurf** [comment]
I also have a couple markdown docs pinned in my sidebar so maybe that is it? Otherwise my setup is pretty standard.

![image](https://user-images.githubusercontent.com/64155612/131553532-1b0def39-9dcf-4dcd-a9a7-a56d54734fe7.png)

**Comment by ddebby** [comment]
Same error when using a markdown file with dataviewjs. The error is from `getPropertyValue` function.

**Comment by elias-sundqvist** [comment]
Can you check if it works in the new release?

**Comment by GitMurf** [comment]
@elias-sundqvist new version looks like it is fixed! Thanks and nice work!
