### ISSUE TITLE
Failed to open sidebar to see and add annotation

### ISSUE THREAD

**Issue by oliwang** [elias-sundqvist/obsidian-annotator#131]
I using Obsidian v0.13.23 on OSX 12.2 with Annotator v0.1.9.

After I installed the annotator plugin and added a pdf file, I realized that the sidebar does not show up. The error messages says "Error: Unable to establish sidebar-host communication channel" and "Failed to execute 'postMessage' on 'Window': Port at index 0 is already neutered."

Is there any way that I can fix this?

<img width="1440" alt="Screen Shot 2022-02-03 at 11 56 18 PM" src="https://user-images.githubusercontent.com/5282363/152379774-e534a608-5f35-46a8-a327-78abdb329be6.png">

<img width="1440" alt="Screen Shot 2022-02-03 at 11 56 33 PM" src="https://user-images.githubusercontent.com/5282363/152379812-a70c835d-592b-4b63-9657-032be51bc23a.png">

Nothing happens when I click on "Show" button.

**Comment by elias-sundqvist** [comment]
I'm not sure if it's the only issue. But I see that you get the error `WeakRef is not defined`. This means that you have an obisidan installation that is using an older version of javascript. Try reinstalling Obsidian using the installer from the website.

**Comment by oliwang** [comment]
After downloading and reinstalling Obsidian from the website, Annotator works perfectly. Thank you for this amazing plugin!
