### ISSUE TITLE
The highlights appear outside block quote

### ISSUE THREAD

**Issue by Missionary2112** [elias-sundqvist/obsidian-annotator#132]
I just installed and used Annotator and found the highlights appear outside the block quote.
![2022-02-15 at 05 21 52 PM (Obsidian)](https://user-images.githubusercontent.com/98799613/154178260-36a5fbb8-4803-4594-bba7-9c9bc0c8453e.jpg)

## Solution: 
- Remove the asterisk `*` beginning and ending of a blockquote
- E.g. >`*`%%PREFIX%%below.28Pro Tools Fundamentals I%%HIGHLIGHT%% ==Co-Installed Plug-Ins== %%POSTFIX%%Avid plug-ins that install with`*`
  - Because I used ITS theme and it causes the bug. It's working fine in default theme.

**Comment by aladmit** [comment]
I close this issue because I don't see this problem appear with ITS theme anymore 👌🏻
