### ISSUE TITLE
Not able to annotate on ios

### ISSUE THREAD

**Issue by Seraphli** [elias-sundqvist/obsidian-annotator#133]
Nice plugin. I saw on the official website that this plugin is mobile compatible. I was trying to use it on my iPhone. But I can not find the way to open it in annotator.

**Comment by elias-sundqvist** [comment]
It should work. I don't have an Iphone, but this is what it looks like on android:

![Screenrecorder--1645035362891.gif](https://user-images.githubusercontent.com/9102856/154330014-d3dcd08d-3fa3-4649-ac81-9f7f3bf98da7.gif)

The plugin is platform agnostic, so it should work the same on iphone.

**Comment by Seraphli** [comment]
https://user-images.githubusercontent.com/1586755/154435482-78e27dca-76ef-4162-a2e2-60eb5623d562.mov

Here is my situation. I test on my iPhone and iPad. They all don't have the option in the menu.

**Comment by elias-sundqvist** [comment]
hmm, that's strange. I suspect that the plugin crashes at some point for you, but it's difficult to tell on mobile since you don't have a debug console.

**Comment by ahmed316dev** [comment]
I am having exactly the same problem, I can't see that Annotate button
i'm running Android 11

**Comment by mbusch-regis** [comment]
I get the same results as @Seraphli on iPad Pro, iOS 16.3.

**Comment by baseliners** [comment]
I'm also not able to get this to work on iOS/iPadOS. Any ideas on how to help debug?

**Comment by aladmit** [comment]
It's a known bug that plugin doesn't work on iOS since iOS 16.3 Unfortunately, I'm stuck with this issue and don't see a way to fix it at the moment😢 The only known workaround is to downgrade iOS to 16.2 or lower.

P.S I'm closing this issue #289 is main issue on this topic.
