### ISSUE TITLE
when opened as md file, the font of the highlights are always italic, which seems inconvienient to read. Any way to avoid this?

### ISSUE THREAD

**Issue by ghweili** [elias-sundqvist/obsidian-annotator#143]
When opened as md file, the font of the highlights are always italic, which seems inconvienient to read. Any way to avoid this?

**Comment by ghweili** [comment]
I just notice that this issue is related to the specific theme one uses. For example, if I use the ITS theme, the text is no longer italic.

**Comment by kalmir** [comment]
Actually I think you were right originally: Annotator automatically inserts marks for italics (`*`). So this is not done via css.

Could we ask for an option to toggle "highlights in italics" on and off?
