### ISSUE TITLE
Request: Setting to change how wide the annotation side bar is?

### ISSUE THREAD

**Issue by ReaderGuy42** [elias-sundqvist/obsidian-annotator#144]
Is there a setting (or would it be possible to add one) so I can change the width of the sidebar with the annotations?
On my bigger monitor it's ok, but on my normal screen I can barely see the actual PDF and the side bar covers almost half the screen.

Also, I had a very hard time getting the plugin to actually find the file. It couldn't find it anywhere aside from the same folder the annotation note is in. (I tried a different folder in the vault, as well as an absolute path on my PC.)

Aside from that, love the plugin!
Thanks :)

**Comment by MILKMILKKING** [comment]
+1 and love the plugin!

**Comment by chrisaldrich** [comment]
The ability to resize the Hypothes.is drawer is already built into the Hypothes.is interface natively. In the top left of the drawer there is a ">" tab that you can drag to resize the annotations window to suit your needs. Clicking on it will allow you to open and close the pane as needed. If it's closed (the icon appears as "<"), you can highlight and choose "annotate" or "highlight" and it will automatically re-open the Hypothes.is interface.

**Comment by MILKMILKKING** [comment]
> The ability to resize the Hypothes.is drawer is already built into the Hypothes.is interface natively. In the top left of the drawer there is a ">" tab that you can drag to resize the annotations window to suit your needs. Clicking on it will allow you to open and close the pane as needed. If it's closed (the icon appears as "<"), you can highlight and choose "annotate" or "highlight" and it will automatically re-open the Hypothes.is interface.

Thank you!
