### ISSUE TITLE
TypeError when opening pdf files stored by Zotero

### ISSUE THREAD

**Issue by alexisthual** [elias-sundqvist/obsidian-annotator#149]
First, thanks a lot for the great plugin! :slightly_smiling_face: 

I am trying to use it in combination with [`obsidian-citation-plugin`](https://github.com/hans/obsidian-citation-plugin) the following way:
1. exporting my references library to a .bib file
2. loading this .bib file using the citation plugin
3. annotate the pdf file and save annotations in the md note created by the citation plugin

However, trying to edit Zotero-stored pdf files with `obsidian-annotator` raises the following error:
```
PDF.js v2.11.249 (build: 95435ed66)
Message: Cannot read property 'getReader' of null
```

It feels to me that this is a permission problem. Indeed, I can move these pdf files to a different folder (say `~/Downloads`), and the plugin will open them.
However, even though I tried to `chmod 777 -R` the folder containing all my Zotero folders, it didn't solve this problem.

Have you experienced anything similar?
I use ubuntu 21.04 and my pdf files are stored under `/home/alexis/snap/zotero-snap/common/Zotero/storage/**/*.pdf`.

Thanks!

**Comment by dermanu** [comment]
I have the same problem.

**Comment by alexisthual** [comment]
Sorry I can't really remember how I solved this issue, but I think using `file://` is indeed what I needed, so I'll close the issue.
Thanks1
