### ISSUE TITLE
Potential CORS issue when trying to use a PDF URL instead of local PDF in my vault

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#15]
It seems maybe some sort of CORS issue with trying to use external PDF links. 

Use this as example: https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-support-and-licensing-guide-datasheet.pdf

![image](https://user-images.githubusercontent.com/64155612/131287420-6b721dbb-cb3e-420c-a44a-de102b6753ef.png)

![image](https://user-images.githubusercontent.com/64155612/131287372-7edf3918-c0af-4e5d-97b3-f928d72d7222.png)

When I tried one on MOBILE (different URL) on iPhone I got the following error (maybe this is a different issue all together):

![image](https://user-images.githubusercontent.com/64155612/131287477-5781485e-d592-4106-be46-d19ebb54d9e2.png)

**Comment by GitMurf** [comment]
Could it at all be related to having the source / URI set as arxiv.org and therefore having conflicting sources / connections and causing some sort of CORS violation? like I called out in this issue: #14 ?

**Comment by GitMurf** [comment]
Ok yeah it definitely looks like a CORS issue as I saw this in the dev console:

![image](https://user-images.githubusercontent.com/64155612/131288066-b78d9b90-b503-4398-934e-627c8d028401.png)

**Comment by GitMurf** [comment]
When I try to do a file from arxiv.org, like the one below, it works.

annotation-target: https://arxiv.org/pdf/1702.08734.pdf

**Comment by elias-sundqvist** [comment]
Yeah, that is most likely a CORS issue. (Arxiv had CORS support). You could always add the pdf to your vault  and enter the vault path instead:

![Screenshot_2021-08-30-07-27-36-351_md.obsidian.jpg](https://user-images.githubusercontent.com/9102856/131289657-9a2f3335-a812-48b5-a765-92097384179e.jpg)
![Screenshot_2021-08-30-07-27-53-702_md.obsidian.jpg](https://user-images.githubusercontent.com/9102856/131289640-fb6edaa9-a551-4690-925a-25667b44f8a6.jpg)

**Comment by GitMurf** [comment]
> Yeah, that is most likely a CORS issue. (Arxiv has CORS support). You could always add the pdf to your vault and enter the vault path instead:

@elias-sundqvist yeah that is what I was afraid of. But I tested it on about 6 different PDFs from different sources and all 6 had the issue. So I am starting to think maybe that will be the pattern for most online PDFs other than somewhere like Arxiv which is made as a PDF repository so likely has CORS configured appropriately knowing many may use it that way.

Licat has talked about some potential ways around CORS in Electron / Obsidian recently.... any ideas on maybe a way around?

**Comment by elias-sundqvist** [comment]
Yeah, true. I could probably implement a CORS workaround for electron. Not sure about mobile though.

**Comment by GitMurf** [comment]
You could post the question asking Licat about it. He said soon he will be providing a CORS workaround through the API. 

Here is some recent conversation about it when I was having problems with Notion CORS: https://discord.com/channels/686053708261228577/840286264964022302/874736528121806868

Here are a few of Licat's key comments:

![image](https://user-images.githubusercontent.com/64155612/131292057-10b2f2d9-ef00-4ff7-847d-6d6fc2806ea2.png)
![image](https://user-images.githubusercontent.com/64155612/131292113-589a1245-c41c-4609-88e0-02c0cfc77337.png)

**Comment by elias-sundqvist** [comment]
Interesting. I'll probably wait for that api to come out then. Should be more reliable than if I implement a workaround myself.

**Comment by GitMurf** [comment]
Yep I agree.

**Comment by elias-sundqvist** [comment]
There have been several issues posted related to CORS issues, It will also be needed if I want to add website annotation support, as suggested in #59, so I ended up implementing a workaround now.
It is available in release 0.1.3
I'll use the official CORS workaround in the Obsidian API whenever it gets released though.

**Comment by GitMurf** [comment]
Oh wow awesome!! I need to get around CORS in a plug-in I’m building. Can you tell me how you did it? And/or point me to where in the code you are handling it? Thanks!

**Comment by elias-sundqvist** [comment]
The relevant code is in commit 6c64cf2d4181a7526ed4f8b83ce34e5b86ccc48a

basically, I try using the `https` library in node if the regular fetch function fails.

**Comment by elias-sundqvist** [comment]
Note that the workaround doesn't work on mobile though.

**Comment by GitMurf** [comment]
Thanks!

**Comment by GitMurf** [comment]
@elias-sundqvist this is working great! My only other suggestion would be, and I'm not sure if it is even possible so feel free to say "it is what it is" haha... but when I try to connect to an external PDF URL that has a CORS issue, it still gives these console errors. Not sure if it is possible to "catch" these errors or not? But I know people (like myself) are OCD about their console so they may see these errors and think there is a problem.

Alternatively if you cannot catch these errors then you could maybe add a little more to your console log that mentions you are using httpsGet and add something like: "Due to CORS issues (see error above) we are trying to get the PDF via httpsGet instead...."

![image](https://user-images.githubusercontent.com/64155612/133147236-69c0934a-099a-4e31-bac0-68b3c81623d3.png)

**Comment by elias-sundqvist** [comment]
The cors error messages are impossible to catch unfortunately, but your second suggestion sounds reasonable.

**Comment by GitMurf** [comment]
Figured as much. Sounds good. Amazing work on how far this has come!

**Comment by sillypoise** [comment]
Hello, dropping here to find out about the state of the CORS issue.
I'm having trouble linking external pdf's.
Tried documents from a CDN as well as random pdf's from other sites. Same "blocked by CORS policy" error appears.

Want to make sure it isn't something on my end and maybe we're still waiting for the CORS workaround in the Obsidian API.

Nice work with the plugin btw, really eager to try it out more! Also +1 for adding `annotator.tv` to the plugin.

Cheers

![image](https://user-images.githubusercontent.com/47010637/156685498-e39a1f61-531c-4fa5-a5d5-c04aba4395a9.png)
---
![image](https://user-images.githubusercontent.com/47010637/156685635-ee4c7e5c-e6e6-4b30-a181-8589ec2c96e0.png)
