### ISSUE TITLE
Can we target files on local computer that are not in our vault?

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#16]
I'm trying to target a PDF like Obsidian does with linking to local files on your computer that are outside your vault with `file://...` do you see this as a possibility down the road? Or do you think we will have to have PDFs copied into our vault?

`annotation-target: file:///C:%5CUsers%5CShawnMurphy%5COneDrive%5C1_Docs%5CResources%5CISVs%5CMSFT%5CSQL%20Server%5CSQL%20Server%202019%20Licensing%20guide.pdf`

![image](https://user-images.githubusercontent.com/64155612/131289652-fba29c95-0199-4315-8d9b-cb7afb3e74ba.png)

**Comment by elias-sundqvist** [comment]
I don't see any reason why it shouldn't be possible. I can probably add support for `file://` urls the next release.

**Comment by GitMurf** [comment]
Wow thanks! @elias-sundqvist you are awesome!! This is seriously cool!

**Comment by elias-sundqvist** [comment]
`file:` protocol support is now part of the new release. 
I have not tested it very much though, so there could be bugs. 
![local file support](https://user-images.githubusercontent.com/9102856/131348942-585ccc4f-cbbf-43a1-97d0-c38e4db47560.gif)

**Comment by wenlzhang** [comment]
Is it also possible to support targeting files stored in DEVONthink databases? It would look something like this: `x-devonthink-item://123...`

**Comment by elias-sundqvist** [comment]
> 
> 
> Is it also possible to support targeting files stored in DEVONthink databases? It would look something like this: `x-devonthink-item://123...`

I don't have a mac, so it would be pretty difficult for me to develop and test. But I'd happily accept a pull request in case someone else wants to add support.

**Comment by GitMurf** [comment]
Doesn’t Devon think just have things stored on your local machine anyways? So can’t you just add the location of the pdf that Devon think stores? It has to sit somewhere locally.

**Comment by elias-sundqvist** [comment]
I'll close this issue since the task has been completed, but feel free to open a new issue regarding DEVONthink.

**Comment by wenlzhang** [comment]
> Doesn’t Devon think just have things stored on your local machine anyways?

@GitMurf Thanks for the suggestion. It's true that one can get an ordinary path of files stored in DEVONthink databases. However, getting the DEVONthink item address would provide a few advantages that I would like to take advange to:

- DEVONthink can show if a file is referenced in another note stored in one of its databases.
- If the file is moved to another folder within the DEVONthink database, the link would not break.

Therefore, it would be great to be able to insert a DEVONthink item link directly, instead of an ordinary file path/address.

**Comment by GitMurf** [comment]
> `file:` protocol support is now part of the new release. I have not tested it very much though, so there could be bugs.

@elias-sundqvist FYI I tested the local files outside obsidian vault and it works beautifully! Thank you!
