### ISSUE TITLE
Cannot install plugin from Obsidian browse section

### ISSUE THREAD

**Issue by yanly007** [elias-sundqvist/obsidian-annotator#171]
I get "Failed to install plugin" when I try to update Annotator in Obsidian.
I tried to uninstall and install again and the issue persists.
Since there is a recent release of the plugin I thought maybe there's an issue with it?

**Comment by aladmit** [comment]
@yanly007 Yeah, you are right, issue was because last release 🤦🏻‍♂️ I corrected release name/tag, it downloads properly now.

Thanks for the issue 👍🏻
