### ISSUE TITLE
Sign up and Log in do not work

### ISSUE THREAD

**Issue by CedrikHarrich** [elias-sundqvist/obsidian-annotator#180]
When clicking on Sign up nothing is happening.
![image](https://user-images.githubusercontent.com/48216280/173093141-275ed5ee-8c21-46b0-96b2-d902e7997f1b.png)

When clicking on Log in I only get this message: ERROR: Failed to open login window
![image](https://user-images.githubusercontent.com/48216280/173093183-8e8e5a7e-1d26-4d6d-a563-859491399be5.png)

Other Links are not working either like: "New support ticket", "Help Topics", "join link" etc.
![image](https://user-images.githubusercontent.com/48216280/173093958-bb964b40-6f05-4bb8-97c1-2faf42861c66.png)

**Comment by JordanChoe** [comment]
I am having the same issue.  New user, running latest Firefox and Obsidian.  Uninstalled and reinstalled the plugin.

**Comment by mbac** [comment]
I'm having the exact same problem…

**Comment by avillani** [comment]
Maybe same as #179 ?

**Comment by aladmit** [comment]
I close this issue because this is how plugin is supposed to work. You can read more about this here https://github.com/elias-sundqvist/obsidian-annotator/issues/38
