### ISSUE TITLE
Add zone annotations

### ISSUE THREAD

**Issue by devnoname120** [elias-sundqvist/obsidian-annotator#190]
Would be super useful for PDF images.

**Comment by huyz** [comment]
What are zone annotations? Do you have a screenshot of an app that does this?

**Comment by huyz** [comment]
Perhaps a dup of https://github.com/elias-sundqvist/obsidian-annotator/issues/40 ?

**Comment by devnoname120** [comment]
> Perhaps a dup of https://github.com/elias-sundqvist/obsidian-annotator/issues/40 ?

Indeed it is!
https://github.com/elias-sundqvist/obsidian-annotator/issues/40#issuecomment-913174774
