### ISSUE TITLE
Add selected text as an alias for block references

### ISSUE THREAD

**Issue by MILKMILKKING** [elias-sundqvist/obsidian-annotator#20]
Add selected text as an alias for block references

For example: I selected in this PDF "nvestment Thesis" as a highlight, the note will be dragged to other notes when the display is: [[NOTE#^6cltnr737q5]] 

![image](https://user-images.githubusercontent.com/69726213/131371486-70378873-76a9-4d70-acba-204a248cb2db.png)

can generate such: [[NOTE#^6cltnr737q5|Investment Thesis]] 
which is the selected field as an alias for the block name.

Because then the content of the block reference can be known during the edit state. If the selected text is too long, perhaps it could also be displayed like this.
[[NOTE#^6cltnr737q5|Investment Thesis Since its inception in 2007......]]

**Comment by elias-sundqvist** [comment]
Not sure if this is what you asked for, but in the new release, it is now possible to drag highlights from the pdf/epub viewer into another obsidian note by holding the <kbd>shift</kbd> key. 
![highlight drag and drop](https://user-images.githubusercontent.com/9102856/132098957-e6850c9f-77a0-4fd5-91ac-e7095cfbea9d.gif)

**Comment by MILKMILKKING** [comment]
Yes, it is! That's what I want! The ability to even drag and drop to other notes now is really great!
