### ISSUE TITLE
Proposed Solution to Epub.js Problems: ReadiumJS

### ISSUE THREAD

**Issue by cmalcantara** [elias-sundqvist/obsidian-annotator#203]
Some issues with Epub.js such as the changing of font size and themes from the reader can be solved by switching to Readium.js

**Comment by aladmit** [comment]
Huh, it has font settings, a few default themes, keyboard shortcuts configuration, layout configuration. And all this right in the UI! @elias-sundqvist have you tried this? Looks neat https://web.hypothes.is/demos/readium/

**Comment by elias-sundqvist** [comment]
Yeah, I looked at readium a while ago, but I never went very far with it. 

Two major downsides are that it is relatively bloated, and that it seems more difficult to control with external javascript than epub.js.

Also, if we just add the ability to inject custom css into epub.js (maybe we can even allow this to be specified in obsidian themes somehow),  we would get color and font customization that is even more powerful than readium even if we keep using epub.js. So I'm not convinced yet that this change would be worthwhile.
