### ISSUE TITLE
Hypothesis blocking requests for resource files?

### ISSUE THREAD

**Issue by BorisAnthony** [elias-sundqvist/obsidian-annotator#204]
EPUB loads, hypthesis UI loads (as far as I can tell) but then none of its features work (login, highlight, annotation, etc…).

Opening the DevTools, Console tells me `https://cdn.hypothes.is/hypothesis/build/styles/highlights.css?5dd56a` and `https://cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js?93d0e1` failed to load.

Network view confirms both are 403'ed.

Loading the URLs from a web browser gives me an XML Access Denied response.

Tried via VPN, same result.

Just me? New situation? Bueller? 😅

**Comment by aladmit** [comment]
That's a common problem with outdated obsidian version 😞 Try to update obsidian **installer** to latest version.
