### ISSUE TITLE
Multiple highlight colors 

### ISSUE THREAD

**Issue by johans3** [elias-sundqvist/obsidian-annotator#210]
We need multiple highlight colors to attribuite different semantic meanings to our highlights, I'd suggest 5/6 diff colors :

- Important (yellow) 
- description (green) 
- citation (blue) 
- research (violet) 
- irrelevant (gray) 
- etc

**Comment by aladmit** [comment]
Yes, I would like to have it too, but to make this possible, it should be implemented on hypothesis side first, as [described in README](https://github.com/elias-sundqvist/obsidian-annotator#annotating).

**Comment by real-jiakai** [comment]
> Yes, I would like to have it too, but to make this possible, it should be implemented on hypothesis side first, as [described in README](https://github.com/elias-sundqvist/obsidian-annotator#annotating).

Looking forward to this feature. ❤️❤️❤️
