### ISSUE TITLE
Latex is not working as before

### ISSUE THREAD

**Issue by Seraphli** [elias-sundqvist/obsidian-annotator#228]
![image](https://user-images.githubusercontent.com/1586755/192853740-c36cb0be-9d27-4d0d-a832-c1ed89263cea.png)
![image](https://user-images.githubusercontent.com/1586755/192853810-ba2a60fc-59a2-48ca-844d-387a44aecfb1.png)

I tried inline form and equation form. Both of them didn't work. I find a related comment here. https://github.com/elias-sundqvist/obsidian-annotator/issues/158

**Comment by Seraphli** [comment]
I have to reverse my version back to 0.1.9 to make latex work. It seems something happened between 0.1.9 and 0.2.0 breaks this feature. 

I think this https://github.com/elias-sundqvist/obsidian-annotator/commit/f484a2abbc64375a6b117691b7dafff02eba184d is the commit that breaks latex.

**Comment by Seraphli** [comment]
@elias-sundqvist @aladmit This might be a minor bug. It will be helpful if you guys can fix this.

**Comment by elias-sundqvist** [comment]
Thanks for reporting the bug. I'll try to fix it sometime next week.

**Comment by Seraphli** [comment]
@elias-sundqvist It has been already 20 days. Any update about this?

**Comment by elias-sundqvist** [comment]
Partially fixed. I can render some equations now, but others are still broken.  Hopefully done soon 🤞

**Comment by Seraphli** [comment]
Another issue is after I upgrade Obsidian to ver 1.0, the annotator seems quite laggy when you are scrolling pages. It even causes Obsidian to stop refreshing the UI. I'm using MacBookPro 19. The annotator was laggy before Obsidian ver 1.0, but it never stuck the UI before. It quite causes some problems. I have to scroll through the pages carefully after the upgrade. I don't know if there is a way to solve this issue in the future.

**Comment by elias-sundqvist** [comment]
I've released a new version of the plugin now, which should fix the latex issue. 
I haven't investigated the lag issue yet. It's not very laggy for me, but my computer is quite beefy.

**Comment by Seraphli** [comment]
Confirm fixed. Another issue occurs after I update the plugin. https://github.com/elias-sundqvist/obsidian-annotator/issues/247
