### ISSUE TITLE
Disable/hide "sign-in/log-in"

### ISSUE THREAD

**Issue by nimo23** [elias-sundqvist/obsidian-annotator#241]
Would be nice to include an option within the config page of obsidian-annotator to hide the following links/buttons within the annotator-pane:
- hide/disable sign-in/log-in
- hide "my groups"
- hide the "Share annotations on this page"-icon

Those things are currently always visible in the pane also for users which does never use the log-in/sign-in.

**Comment by elias-sundqvist** [comment]
Should be fixed in the latest relase
