### ISSUE TITLE
The build process is a bit difficult

### ISSUE THREAD

**Issue by HardwayLinka** [elias-sundqvist/obsidian-annotator#250]
Hey @aladmit, I love this project. When I was going to add functionality to this project, I found it a little hard to build and I ended up failing. The error message is as follows:

![image](https://user-images.githubusercontent.com/45873697/198986744-e8c6e89e-1c83-4c1c-ba51-d1fbcb243989.png)

environment:
win 11 22H2
annotator 0.2.7
obsidian v1.0.3

Could you please tell me what goes wrong? BTW, I would like to know where are the build steps for this project.

**Comment by talenelat-elin** [comment]
Seconded. And could you please make it detailed enough for programming noobs like me to follow? :)

**Comment by HardwayLinka** [comment]
My build process：

- Install node.js v18.12.0
- Install yarn v1.22.19
- Install MinGW
- git clone https://github.com/elias-sundqvist/obsidian-annotator
- git submodule init
- git submodule update
- Modify according to README_DEV.md
- npm install in obsidian-annotator
- npm install in submodules
- npm run build submodules
- npm run build obsidian-annotator (failed here)

**Comment by HardwayLinka** [comment]
## About the build steps for this project on Windows

### What you need to know before building
[obsidian-annotator](https://github.com/elias-sundqvist/obsidian-annotator) has a [submodules](https://github.com/hypothesis/client), so before building [obsidian-annotator](https://github.com/elias-sundqvist/obsidian-annotator), you need to build its [submodules](https://github.com/hypothesis/client).

The [submodules](https://github.com/hypothesis/client) contains a [development guide](https://h.readthedocs.io/projects/client/en/latest/developers/) to help you [build](https://h.readthedocs.io/projects/client/en/latest/developers/developing/#running-the-client-from-h). That dev guide tells us to execute `make dev` to build the [project](https://github.com/hypothesis/client),  [which fails on windows](https://github.com/elias-sundqvist/obsidian-annotator/issues/250#issue-1429611572) because windows lacks some commands on linux, see [here](https://github.com/hypothesis/client/issues/4918#issuecomment-1298304488). 

Looking closely at the Makefile in the root directory of the subproject, 

![image](https://user-images.githubusercontent.com/45873697/199413206-7f11a378-02f4-4379-83f7-76b87eb279c3.png)

you will find that `make dev` actually executes `yarn install`, so we can execute `yarn install` directly in the root directory of the subproject to avoid executing redundant Linux commands.

### Prerequisites
- [git](https://git-scm.com/)
- [Node.js](https://nodejs.org/en/)
- [Yarn](https://yarnpkg.com/lang/en/)

### Building
1. `git clone https://github.com/elias-sundqvist/obsidian-annotator.git`
2. `git submodule init`
3. `git submodule update`
4. `yarn install` in the submodules
5. Modify according to [README_DEV.md](https://github.com/elias-sundqvist/obsidian-annotator/blob/master/README_DEV.md)
6. `npm install` in obsidian-annotator
7. `npm run build` in obsidian-annotator

When you see the information in the figure below after the build, it is successful

![image](https://user-images.githubusercontent.com/45873697/199418707-f16c3dbc-fae1-4c0a-ad5f-3d3f4a40b7c5.png)

---
Hey @talenelat-elin, the above may help

**Comment by aladmit** [comment]
Hi @HardwayLinka 👋🏻 I never tried to build the project on Windows, so I'm not sure what kind of problem you would encounter on this path. I've build it a few times on Windows WSL, worked great without any modifications from `README_DEV.md`

## Building steps
1. git clone https://github.com/elias-sundqvist/obsidian-annotator.git
2. git submodule init
3. git submodule update
4. `npm install` in obsidian-annotator
5. `npm run build` in obsidian-annotator. It would install deps and build hypothesis submodule too. We use `build` to build everything from scratch, but rebuild hypothesis on every change takes too long, so during development we use `rpm run quick-build`. This command builds only plugin itself.

## Development process advices
### Hot Reload
You can create  your own vault for tests and live reload plugin into it. First you need to create vault and install `obsidian-annotator`, than you have two options for plugin reload:

1. `npm run dev` – rebuild plugin on every change, but you need to reopen test vault to see the difference
    1. Install `obsidian-annotator` into your test vault
    1. create `.vault_plugin_dir` file with path to plugin `inside` of your test vault. Example: `/test-vault/.obsidian/plugins/obsidian-annotator`.
    1. `npm run dev`
3. Hot reload plugin(**I prefer this way**) – rebuild plugin on every change and automatically reload plugin inside your test vault
  1. Manually install [Hot reload plugin](https://github.com/pjeby/hot-reload) into you test vault. **Enable it**.
  3. Link plugin's code into test vault. So `<vault path>/.obsidian/plugins/obsidian-annotator` would refer to plugin repository.
  4. run `npm run dev` or `npm run quick-build`. On every change in `main.js` or `manifest.json` Hot reload will reload `obsidian-annotator` in test vault.

### Linters and types
I'm trying to make code stricter and safer, please run `npm run betterrer` from time to time to see if your changes made code worse or better. If you made a positive change, run `npm run betterer -- --update` to update betterer results.

Unfortunately, sometimes betterrer starts to warn you about code parts you haven't even touched, in this case you can run `npm run betterer -- --update` too, to make `betterer` think it okay to have this errors.

---

P.S. Is it useful enough to make a contribution guide out of it?

**Comment by HardwayLinka** [comment]
Hey @aladmit, [what you wrote](https://github.com/elias-sundqvist/obsidian-annotator/issues/250#issuecomment-1300743736) is very detailed and may help a lot of developers! 

If you want to make a contribution guide，could you include [what I wrote](https://github.com/elias-sundqvist/obsidian-annotator/issues/250#issuecomment-1299653893)? Because using [obsidian-annotator](https://github.com/elias-sundqvist/obsidian-annotator) on windows always has problems, see https://github.com/elias-sundqvist/obsidian-annotator/issues/172, https://github.com/elias-sundqvist/obsidian-annotator/issues/230, I guess maybe debugging on windows can find the problem.
