### ISSUE TITLE
DATAVIEW SYNTAX

### ISSUE THREAD

**Issue by viperbbb** [elias-sundqvist/obsidian-annotator#255]
Can you give an example of Dataview syntax ?   How to start?  Gif is rolling too fast, I  can't get it.

**Comment by aladmit** [comment]
Sure!

```
annotation-target:: [[2022 State of DevOps DORA.pdf]]
```

Instead of link you also can use a path or URL to a file.

**Comment by viperbbb** [comment]
thanks a lot.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrey ***@***.***&gt;; 
发送时间: 2022年11月10日(星期四) 凌晨4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [elias-sundqvist/obsidian-annotator] DATAVIEW SYNTAX (Issue #255)





 
Sure!
 annotation-target:: [[2022 State of DevOps DORA.pdf]]  
Instead of link you also can use a path or URL to a file.
