### ISSUE TITLE
What does "Status Bar Text" in the bottom footer (Status Bar) do?

### ISSUE THREAD

**Issue by raiwh** [elias-sundqvist/obsidian-annotator#27]
This is a question - I am unsure exactly what the "Status Bar Text" item does in the status bar.  Currently it appears to do nothing (that I can see) and simply takes up valuable real estate in the status bar.  For now I have disabled it with CSS (display: none;) but worry that I am missing out on some key functionality.  Wondering if you can advise.  Thanks.

**Comment by elias-sundqvist** [comment]
Do you have the latest version installed. It should have been removed in the latest release? See #17

**Comment by raiwh** [comment]
aah....probably not.  Will update and check.  Thanks for quick response.

**Comment by raiwh** [comment]
Thanks...Updated to latest version and status bar text is no more.  😀
