### ISSUE TITLE
Annotations immediately disappear - on three different devices

### ISSUE THREAD

**Issue by fbauer-kunbus** [elias-sundqvist/obsidian-annotator#276]
Sorry to say this - but this plugin obviously has a major problem ... like others already wrote: the annotations disappear as soon as they have been saved and I jump to some other note and come back. I then just get the 'There are no annotations in this group.
Create one by selecting some text and clicking the  button.' message, and this is it. This happens on three different devices (Win 10 PC, Android 13 Tablet, Android 10 Smartphone). If I look in md mode into the annotation file, the data is present there - but it doesn't get loaded and rendered again.
Above that: on the tablet and the smartphone it still has many bugs and uses way to much CPU. In 'Pagination' mode I also geht the big 'chevron_left' and 'chevron_right' text shown where the paging controls should be. Instead of the three lines burger menu, there is the text 'menu' shown. This already has been posted here as a bug in October by other users without any reaction. 

This whole plugin is a great idea, but suffers from not enough action and error fixing on the developer(s)' side. 
No offense - please simply tell the community if you have not enough time to work on it so we don't waste time with annotations we cannot work with in the end.

**Comment by yarub123** [comment]
@fbauer-kunbus Mine are disappearing too, did you ever figure out what it was?

**Comment by aladmit** [comment]
Yeah, plugin isn't perfect and not 100% stable, what's why version is still 0.*.* But despite that, it does some useful things and helps me almost daily. So in return I'm improving it step by step on pure enthusiasm when I have free time and resources.

If you wanna help, PRs and helping other people with issues are always welcomed. But if you don't, "don't waste time" and walk away.
