### ISSUE TITLE
Broken on iPad after update to 0.2.9.

### ISSUE THREAD

**Issue by sousamaf** [elias-sundqvist/obsidian-annotator#284]
The plugin stopped working on iPad after updating to version 0.2.9. It's possible install, but fail when try enable.

**Comment by taofuns** [comment]
same problem

**Comment by AskSnehasish** [comment]
Not only iPad, but the iPhone app is broken after 0.2.9 update.

**Comment by msackeygh** [comment]
Yes, I can report the same issue. The error is something about failed to load plug-in. Hopefully a fix is coming soon. I depend on this across different platforms: iOS, iPadOS, Windows, and macOS. Thanks!

**Comment by aladmit** [comment]
Thanks everyone for reporting this! 0.2.10 was released with fix. I tested it on iPhone with iOS 16.2, looked like everything works except new feature with jump from link to annotation.

**Comment by AskSnehasish** [comment]
I just verified it and it works well on the iPhone and iPad now. Thanks for your proactiveness.
