### ISSUE TITLE
v0.2.10 can't work on macOS

### ISSUE THREAD

**Issue by taofuns** [elias-sundqvist/obsidian-annotator#286]
Can not load PDF on Mac, but it can work on iPad.
> PDF.js v2.11.249 (build: 95435ed66)
> 信息：Failed to fetch
![image](https://user-images.githubusercontent.com/80188597/212033021-99c3c1bf-8b66-43d5-9e87-4f1d78f32de5.jpeg)

**Comment by ryanwwest** [comment]
Works for me on macos

**Comment by taofuns** [comment]
after a day, it works normally.
