### ISSUE TITLE
Annotate option not showing up in note options

### ISSUE THREAD

**Issue by spasm** [elias-sundqvist/obsidian-annotator#29]
I've tried plugin versions 0.0.5, 6, and now 7 and none of them create the "Annotate" menu option.  Am I missing a piece of setup?

macOS 11.5.2 and using Obsidian 0.12.12

Attached is a quick video of a vanilla Obsidian install with v0.0.7 of the plugin.

![annotate-missing](https://user-images.githubusercontent.com/10431596/131735043-a567405d-966a-41b8-b63f-dcd964340fed.gif)

**Comment by elias-sundqvist** [comment]
In order to use the dataview syntax `annotation-target:: url`, you need to install the Dataview plugin. 
Otherwise you have to specify the annotation target in the frontmatter of your note, like so:

```md
---
annotation-target: url
---
```

**Comment by spasm** [comment]
> In order to use the dataview syntax `annotation-target:: url`, you need to install the Dataview plugin.
> Otherwise you have to specify the annotation target in the frontmatter of your note, like so:
> 
> ```lisp
> ---
> annotation-target: url
> ---
> ```

Oh snap, you're absolutely correct!  Thanks, works like a charm now!
