### ISSUE TITLE
[IDEA] Options for PREFIX and POSTFIX

### ISSUE THREAD

**Issue by aproddick** [elias-sundqvist/obsidian-annotator#30]
Hi, 
Great work here. Just an idea - I'd love the option to be able exclude the postfix and prefix from the highlighted text, if this is possible. It makes the markdown just a bit messy. Not sure if this is feasible, but might make a nice checkbox option. 
Cheers!

**Comment by elias-sundqvist** [comment]
Sure. I can't remove it from the JSON blob though. 
I can also make the `==` `==` wrapping of the highlight optional.

**Comment by aproddick** [comment]
Oh yes. Both would be good

**Comment by elias-sundqvist** [comment]
This has now been added in the new release

**Comment by aproddick** [comment]
Love it! Thanks- much a much cleaner result.
