### ISSUE TITLE
Stopped Working for Mobile

### ISSUE THREAD

**Issue by patrickongwong** [elias-sundqvist/obsidian-annotator#300]
I've been using this in Obsidian Mobile for the iPad and iPhone. Recently it has stopped being able to load. Still works perfectly for the Mac Though

**Comment by aladmit** [comment]
It has something to do with iOS 16.3 update, but I'm still don't understand what exactly went wrong and how to fix it :( The only workaround at the moment is to downgrade to iOS 16.2.

Main issue about this is #289 , I recommend to subscribe to it to state up to date.
