### ISSUE TITLE
The plugin does not work on the mobile version (iOS iPad)

### ISSUE THREAD

**Issue by Akira7118** [elias-sundqvist/obsidian-annotator#309]
The plugin is unable to open or work in the annotation mode on the mobile version (latest version of the plugin, iOS).

**Comment by robercoding** [comment]
I have the same issue but on Android, Samsung Tablet S7 FE. I tested it on a PC with the same URL just in case and it's working :/

**Comment by aladmit** [comment]
@Akira7118 It's a issue with iOS 16.3(read #289 for details). Have you tried to update iOS to 16.4?

**Comment by aladmit** [comment]
@robercoding The only advice I can give is write URL in quotes. Like this: `annotation-target: "https://..."` Maybe it has something to do with symbols in URL. Unfortunately, I don't have an android device and really look into it.

**Comment by robercoding** [comment]
Hey @aladmit thank you for the advice. 
I gave it another try and realized that the URL wasn't correct. My bad all good on android! Sorry for the alarm :D
