### ISSUE TITLE
Local install of Hypothesis?

### ISSUE THREAD

**Issue by rickcecil** [elias-sundqvist/obsidian-annotator#312]
How easy/hard would it be to connect the hypothesis plugin to a locally hosted version of hypothesis? So I would still be annotating epub and pdf in Obsidian, but the annotations would be stored in a local version of the hypothesis server. 

Curious about level of difficulty and any pointers on where to start -- if it is even possible.

Thanks!

**Comment by aladmit** [comment]
@rickcecil No idea😄 I never used local hypothesis server, but I think write a new plugin would be easier, than changing this one. In theory you only need to set API endpoints correctly before packing hypothesis into a plugin.

https://h.readthedocs.io/projects/client/en/latest/developers/envvars.html

P.S. We can continue discussion here, but I'm closing this issue as not related to the plugin.

**Comment by Aurelyano** [comment]
Thanks for your reply!
I'd like to write a pdf annotator like this for vscode. Now I have pdf-redering done based on pdf.js. But I have no idea how to  use hypothesis's API to highlight and write it to local file.
It seems like truely a lot of files from hypothesis in this repo, if I only need pdf-annotation, which part should I include and set the corresponding APIs?

**Comment by Aurelyano** [comment]
Thanks for your reply!
I'd like to write a pdf annotator like this for vscode. Now I have pdf-redering done based on pdf.js. But I have no idea how to  use hypothesis's API to highlight and write it to local file.
It seems like truely a lot of files from hypothesis in this repo, if I only need pdf-annotation, which part should I include and set the corresponding APIs?
