### ISSUE TITLE
Feature Request: Single page view

### ISSUE THREAD

**Issue by YousufSSyed** [elias-sundqvist/obsidian-annotator#316]
I'd like to be able to read an ebook as just one page at a time rather than have it split into two.

**Comment by aladmit** [comment]
Isn't scroll view already does you want?

<img width="776" alt="Screenshot 2023-05-05 at 22 45 17" src="https://user-images.githubusercontent.com/4015182/236555141-4a954775-8f4b-4571-88c7-83ff34bcd4bb.png">

**Comment by YousufSSyed** [comment]
@aladmit No. I want it to have the epub split into pages, that I navigate horizontally, but instead of showing two split parts, I want it to be one part, does that make sense?

**Comment by JaydenElliott** [comment]
If you click the 2 arrows then `no spreads` you will get a single page view. 
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/53299144/c54fd713-9a4e-4a1d-bedf-38327b6c93bf)

Is this what you meant?
