### ISSUE TITLE
Feature Request: Sizing the Annotation Sidebar

### ISSUE THREAD

**Issue by MrBomber0x001** [elias-sundqvist/obsidian-annotator#324]
Annotation sidebar can't be freely resized, it's just opens to certain width or closes.
We need to freely resize the sidebar.

![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/42917814/b60e01a1-2624-482c-8852-86459b258873)

**Comment by Jiale-Cheng** [comment]
I also need this feature to resize the sidebar, and it's better that we can adjust the font size of the annotations in the sidebar freely!

**Comment by Luiz-nyan** [comment]
But bros, we can freely resize the sidebar.

https://github.com/elias-sundqvist/obsidian-annotator/assets/40703441/7c69de94-0f0f-4caf-98db-4c941174c909

**Comment by Jiale-Cheng** [comment]
> But bros, we can freely resize the sidebar.
> 
>  2023-07-26.08-12-45.mp4

Oh I didn’t notice that! Thanks for the reminder, It helps me a lot!

**Comment by NeumoNeumo** [comment]
> But bros, we can freely resize the sidebar.
> 
>  2023-07-26.08-12-45.mp4

If this helps to solve your problem, close this issue please. :smile:  @MrBomber0x001
