### ISSUE TITLE
[idea] Read & write as embedded annotations?

### ISSUE THREAD

**Issue by cztuc** [elias-sundqvist/obsidian-annotator#33]
Hi there,

1) It seems those embedded annotations of pdf files are not recognized. This will probably limit the motivation to migrate to `obsidian annotator`, when one already has a large library of pdf files and the annotations are embedded via his/her familiar tools, like Okular or Adobe Acrobat. 

2) Also, it will be excellent to have the option to save annotations as embedded.

Thanks again for the plugin.

(I'm probably being too greedy with this plugin; please feel free to omit if this idea seems not right in your plan.)

**Comment by elias-sundqvist** [comment]
Yeah, I can see how that might limit the motivation to use the plugin. Unfortunately, I don't think this feature request is feasible. Hypothesis annotations work quite differently from regular pdf annotations. 

If Hypothesis adds such support I will upgrade the plugin to also have this support, but I wouldn't hold my breath for that happening soon, if at all. 

Something like what is requested in #25 might be possible for me to implement long-term. This would be a one-way feature though. I don't think I can create Hypothesis annotations from the embedded annotations in a pdf.

**Comment by cztuc** [comment]
Thanks very much for your input.

I think the current integration of zotero/[zotfile](https://github.com/jlegewie/zotfile) and obsidian is a bit redundant/odd. That's why I'm a bit greedy with this plugin and hope to see a perfect replacement. 

BTW, maybe zotfile could give you some inspiration in terms of annotations? Or is it possible to zotfile's APIs in this plugin?
