### ISSUE TITLE
Yo bro

### ISSUE THREAD

**Issue by ADXIHacker** [elias-sundqvist/obsidian-annotator#334]
I saw your profile on Spotify, I would REALLY love it if you could share all of Minami's songs that you have 
Much appreciated ❤️
Also I will be using this in the future, once I get my laptop fixed 😎💯❤️🔥

**Comment by elias-sundqvist** [comment]
Hi.  Glad to hear other people enjoying Minami's music :) 
One good location to find more of her songs is at 
https://minami-collections.netlify.app/
Happy listening!
