### ISSUE TITLE
Error when enabling community plugin

### ISSUE THREAD

**Issue by shampto3** [elias-sundqvist/obsidian-annotator#34]
I'm trying to install obsidian-annotator via the community plugins menu. I'm able to install it, but when I click "enable" I get the error message "Failed to load plugin obsidiain-annotator".

## Console logs

After installing but before clicking "enable"
```
Annotator: styles.css not found
```

Each time I click "enable"
```
Plugin failure: obsidian-annotator TypeError:
Zu.substring(...).replaceAll is not a function
    at anonymous (eval at <anonymous> (app.js:1), <anonymous>:49031:193)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
```

## Other context that might help

I don't have too complex of a setup. I did try to manually install this plugin the other day before it was added to the community plugins list, but I couldn't get it to open a PDF so I decided to remove it and try again later. I don't think that would cause any issues, but I'm mentioning it here just in case.

## Video

I recorded a video of the error. Hopefully it helps.

https://user-images.githubusercontent.com/8238593/131917682-2e325aaf-1bb0-4854-8a0d-7bdc18365305.mp4

Let me know if you need anything else from me to help you debug this.

**Comment by cztuc** [comment]
Just a comment: maybe try to remove the plugin's folder, i.e. `your_vault/.obsidian/plugins/`, before you install from Community plugins? I just installed annotator like an hour ago from Community plugins and everything goes well so far.

**Comment by shampto3** [comment]
@cztuc thanks for the idea. I just deleted the whole `plugins` folder entirely and I'm still getting the same error when I try to enable annotator after reinstalling. 🙁

**Comment by elias-sundqvist** [comment]
Another thing that comes to mind is that the function `replaceAll` is only supported for newer versions of NodeJS.
Could you check two things in the console:
* What do you get when you write `process.version`?
* Are you able to do `"abab".replaceAll("b","c")`?

I have kind of assumed that the node version will be the same for all users, but maybe that isn't the case.

**Comment by shampto3** [comment]
@elias-sundqvist oh good idea!

`process.version` -> 12.13.0

Running `replaceAll` in the console gives me an error that it is not a function, so it looks like you are correct. I wonder if me using node on my machine has thrown off whatever obsidian automatically uses. 🤔

**Comment by elias-sundqvist** [comment]
Ok. That's probably the issue then.
I'll try to transpile the code so that it is compatible with older versions.
Should be done before the weekend.

**Comment by shampto3** [comment]
Thank you @elias-sundqvist!

**Comment by elias-sundqvist** [comment]
Not sure if it is fixed now, but I hope so. 

Transpiling the code turned out to be a bit tricky, so instead, I added a library called core-js which is supposed to add the missing methods and classes. I couldn't test if it fixed anything though, since my obsidian installation already uses a newer version of node.

Please test it out when you get the time and tell me how it went 🤞

**Comment by shampto3** [comment]
@elias-sundqvist it's working great now! Thanks for fixing it. I'm really excited to use this. 💯💯
