### ISSUE TITLE
Annotator not renderring properly 

### ISSUE THREAD

**Issue by PrithiPal** [elias-sundqvist/obsidian-annotator#356]
**Problem**: Obsidian Annotator plugin not rendering properly on obsidian screen.
**Details**:
  1. When I create a new annotator page ( After creating new page --> Add property with `annotator-target` and `annotator-target-type` ) and switching to `Annotate` in Options ( three dots ) 
  2. Index panel on left side and Scroll view for pages renders, but not current page itself. When I click on of the pages on Scroll View, it renders the page, but disappears after I click on the page 

**Screenshot Examples**:
- Page Not renders on newly created pdf
![Screenshot 2023-12-12 095655](https://github.com/elias-sundqvist/obsidian-annotator/assets/22536182/e2df2a3d-3711-4894-8485-227fcc6546b9)
- Page visible upon clicking in Scroll view, but disappears when click in page area.
![Screenshot 2023-12-12 095926](https://github.com/elias-sundqvist/obsidian-annotator/assets/22536182/3ab5cf55-b5c1-4b71-9849-bceabcb04d22)

**System Info**
Obsidian Version: `v1.5.1`
Annotator Plugin version: `0.2.10`

**Comment by dalibord** [comment]
I have the same issue in v1.5.2

**Comment by peterkehlerjr** [comment]
same here in v1.5.2

**Comment by LespiletteMaxime** [comment]
Same for me v1.5.2

**Comment by ravitxyz** [comment]
+1

**Comment by Wcdaren** [comment]
+1

**Comment by stoweboyd** [comment]
Me too. Totally unusable.

**Comment by CitoyenYang** [comment]
Me too, after updating to v1.5.3

**Comment by L1uYun** [comment]
Me too, after updating to v1.5.3

**Comment by skittleskittles** [comment]
Same for v1.5.3

**Comment by Marshallleung** [comment]
same for 1.5.13

**Comment by RijoRoriz** [comment]
Same here, I need to roll back obsidian to v1.4.16 to make it work again.

**Comment by eugenekavalchuk** [comment]
+1, help please

**Comment by eugenekavalchuk** [comment]
> Same here, I need to roll back obsidian to v1.4.16 to make it work again.

How did you fix it? I rolled it back, but I'm still facing the issue

**Comment by PrithiPal** [comment]
Looks like @RijoRoriz is referring to obsidian version 1.4.16 and not "annotator" plugin version which I mistaken earlier.

**Comment by eugenekavalchuk** [comment]
@elias-sundqvist, could you please check the issue? It has really broken a lot of work

**Comment by RijoRoriz** [comment]
> Looks like @RijoRoriz is referring to obsidian version 1.4.16 and not "annotator" plugin version which I mistaken earlier. By the way, looks like some html tags are preventing from blob ( file abstraction in browser ), to be loaded by annotation plugin !

Yeah, I was referring to the Obsidian version, not the annotator plug-in. 

@eugenekavalchuk maybe you can do the same temporarily.

**Comment by eugenekavalchuk** [comment]
> > Looks like @RijoRoriz is referring to obsidian version 1.4.16 and not "annotator" plugin version which I mistaken earlier. By the way, looks like some html tags are preventing from blob ( file abstraction in browser ), to be loaded by annotation plugin !
> 
> Yeah, I was referring to the Obsidian version, not the annotator plug-in.
> 
> @eugenekavalchuk maybe you can do the same temporarily.

Maybe I made a mistake? I downloaded versions 1.4.16 and 1.4.14, but nothing happened. The plugin is still broken. 

<img width="289" alt="CleanShot 2023-12-27 at 00 04 29@2x" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/84385366/1052aa21-4c66-4f7a-a35c-54facbfba9be">

**Comment by RijoRoriz** [comment]
> > > Looks like @RijoRoriz is referring to obsidian version 1.4.16 and not "annotator" plugin version which I mistaken earlier. By the way, looks like some html tags are preventing from blob ( file abstraction in browser ), to be loaded by annotation plugin !
> > 
> > 
> > Yeah, I was referring to the Obsidian version, not the annotator plug-in.
> > @eugenekavalchuk maybe you can do the same temporarily.
> 
> Maybe I made a mistake? I downloaded versions 1.4.16 and 1.4.14, but nothing happened. The plugin is still broken.

You don't need to download the obsidian again. Just turn off the "Automatic updates":
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/21692369/bcda51d6-08cf-437c-8282-8b07353445bd)

and delete the file ".asar" with the version:

Win: %appdata%/obsidian/obsidian-0.xx.xx.asar
Mac: ~/Library/Application Support/obsidian/obsidian-0.xx.xx.asar
Linux: ~/.config/obsidian/obsidian-0.xx.xx.asar

restart the obsidian after that!

**Comment by ginozhu8** [comment]
+1

**Comment by KristianS93** [comment]
Same had to roll back to 1.4.16, all annotations are saved in markdown, however, I cant view them in the annotator, very unfortunate.

**Comment by andreaskrath** [comment]
+1

**Comment by dytan** [comment]
extractly the problem, +1 with obsidian 1.5.3

**Comment by RockRockWhite** [comment]
same issue in 1.5.3

**Comment by SMyPresious** [comment]
same issue in 1.5.3

**Comment by osrich** [comment]
+1 in 1.5.3

**Comment by FeelLiao** [comment]
same issue in 1.5.3
hope to be addressed

**Comment by ZhouO-v-O** [comment]
same issue in 1.5.3
hope to be addressed

**Comment by christiansmith** [comment]
@RijoRoriz thanks for the details. I would have died from panic without a short term fix.

**Comment by rryain** [comment]
+1 in 1.5.3

**Comment by Bingyudengren** [comment]
+1 v1.5.3

**Comment by terizhao** [comment]
@RijoRoriz thanks for the short-term fix! Real MVP

**Comment by WilliamsJack** [comment]
It looks like this is due to a new CSP added to Obsidian's `index.html` in 1.5:

```html
<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com">
```

I haven't been able to fix the plugin directly, as it's a bit out of my area of expertise, but I did confirm the cause of the issue by unpacking `obsidian-1.5.3.asar`, removing the CSP from `index.html` and repacking it, allowing Obsidian Annotator to run on 1.5.3.

![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/30068301/1dafe69e-9aae-4c0b-b86c-0136290aff08)

**Comment by TimS-ml** [comment]
@WilliamsJack Thank you!!! Works for me.

**Comment by stoweboyd** [comment]
Could you share the repacked asar?

**Comment by TimS-ml** [comment]
@stoweboyd NP
[obsidian-1.5.3.asar.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13798493/obsidian-1.5.3.asar.zip)

**Comment by Mahgozar** [comment]
> @stoweboyd NP [obsidian-1.5.3.asar.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13798493/obsidian-1.5.3.asar.zip)

this solved the problem for me as well, thank you for this contribution 
for anyone that wants to solve this in arch with the packaged installed from the AUR -> you can find the .asar file here -> /usr/lib/obsidian/  
rename the file titled "obsidian.asar" to something else so the program doesn't read it and replace it with the file in the file above, then rename it to "obsidian.asar" so the program reads it while loading 
for some reason whenever i try to edit the .asar file using nano the program can't read it afterwards 
hope it helps

**Comment by PxaMMaxP** [comment]
I once wrote a shell and a Powershell script. You just have to run it in the right directory. I wasn't entirely comfortable taking over the .asar file from someone else 😅

It is sufficient to add `blob:` to the CSP header. The script does that. Alternatively, the line should be changed as follows: `<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com blob:">`

First you have to install **npm** (google is your friend) and then install asar with `npm install -g asar`.

At least for me under Windows it made sense to reinstall Obsidian once over the old installation.
Otherwise it loads the .asar file from another folder.

So the original is located under `C:\Users\[UserName]\AppData\Local\Obsidian\resources`

Copy the script to this folder and execute it. 

The original .asar file remains as a backup and only `blob:` is added to the corrected one.

Unfortunately, I do not know where the files are located under Linux/Mac. However, I have tested the shell script under Linux and it does what it should. 

Maybe someone else can tell me which paths are the right ones under Linux/Mac.

[AddBlobToCSP.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13799332/AddBlobToCSP.zip)

**Comment by BaoDoanUit** [comment]
I've solved this on Ubuntu with version 1.5.3
1. Delete the old *.asar 
sudo rm -rf ~/.config/obsidian/obsidian-1.5.3.asar

[obsidian-1.5.3.asar.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13803802/obsidian-1.5.3.asar.zip)
2. Unzip file and run.
sudo cp ~/Download/obsidian-1.5.3.asar ~/.config/obsidian/
Then restart Obsidian

**Comment by MatanRubin** [comment]
Anyone knows how to do the same on macOS?

**Comment by stone-sail** [comment]
for macOS, I've solved this as follows: 
1. cd ~/Library/Application\ Support/obsidian/ 
2. open obsidian-1.5.3.asar with vim or other editor
3. comment the line contains "<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com blob:"> "

**Comment by stone-sail** [comment]
I have successfully solved this problem on macOS related to Obsidian, with thanks to @WilliamsJack. The steps are as follows:
1. Open the Terminal application.
2. cd ~/Library/Application\ Support/obsidian/
3. Open the file "obsidian-1.5.3.asar" using a text editor like vim or any other editor of your choice.
4. Locate the line that contains "<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com blob:">".
5. Comment out the line by adding a comment symbol (e.g., "") 
6. Save the changes and close the editor.
7. Restart the Obsidian application.

**Comment by MatanRubin** [comment]
@stone-sail worked for me on macOS. Thanks!

**Comment by RyotaUshio** [comment]
Looks like this?

https://forum.obsidian.md/t/content-security-policy-header-in-obsidian-1-5-3-breaks-plugin/73889/2?u=ush

**Comment by cengizyu** [comment]
> "I wrote"* a shell and a Powershell script. You just have to run it in the right directory. I wasn't entirely comfortable taking over the .asar file from someone else 😅
> 
> It is sufficient to add `blob:` to the CSP header. The script does that. Alternatively, the line should be changed as follows: `<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com blob:">`
> 
> First you have to install **npm** (google is your friend) and then install asar with `npm install -g asar`.
> 
> At least for me under Windows it made sense to reinstall Obsidian once over the old installation. Otherwise it loads the .asar file from another folder.
> 
> So the original is located under `C:\Users\[UserName]\AppData\Local\Obsidian\resources`
> 
> Copy the script to this folder and execute it.
> 
> The original .asar file remains as a backup and only `blob:` is added to the corrected one.
> 
> Unfortunately, I do not know where the files are located under Linux/Mac. However, I have tested the shell script under Linux and it does what it should.
> 
> Maybe someone else can tell me which paths are the right ones under Linux/Mac.
> 
> [AddBlobToCSP.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13799332/AddBlobToCSP.zip)
> 
> * ChatGTP is your friend 🥲

Solved it for me, thanks.

**Comment by eugenekavalchuk** [comment]
> I have successfully solved this problem on macOS related to Obsidian, with thanks to @WilliamsJack. The steps are as follows:
> 
> 1. Open the Terminal application.
> 2. cd ~/Library/Application\ Support/obsidian/
> 3. Open the file "obsidian-1.5.3.asar" using a text editor like vim or any other editor of your choice.
> 4. Locate the line that contains "".
> 5. Comment out the line by adding a comment symbol (e.g., "")
> 6. Save the changes and close the editor.
> 7. Restart the Obsidian application.

What is 4 step?

**Comment by aladmit** [comment]
Damn, I don't see how to make a quick fix for that. In my understating plugin requires complete rewrite from scratch to remove fetching resources with blob 😞

**Comment by atomwww** [comment]
> @stoweboyd NP [obsidian-1.5.3.asar.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13798493/obsidian-1.5.3.asar.zip)

It worked in windows10 obsidian-1.5.3! Thank you.

**Comment by PrithiPal** [comment]
> 2\. [obsidian-1.5.3.asar.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13803802/obsidian-1.5.3.asar.zip)

I used the mentioned obsidian-1.5.2.asar.zip, removed old one, replace with above and restarted obsidian. Annotator properly render now, but content is empty

**Screenshot**
<img width="1040" alt="Screenshot 2024-01-03 at 11 15 03 PM" src="https://github.com/elias-sundqvist/obsidian-annotator/assets/22536182/5a7793bb-e8db-42fc-a332-e6dcb5d507ac">

Obsidian version `1.5.3`
Annotator version `0.2.10`

**Comment by RyotaUshio** [comment]
FYI, you might want to try a new plugin of mine called [PDF++](https://github.com/RyotaUshio/obsidian-pdf-plus) until this problem gets fixed fundamentally. It is based on Obsidian's native PDF support and allows you to make sidenotes as pure markdown, so you will not lose your annotations even if the plugin stops working as long as Obsidian's PDF functionality keeps working.

**Comment by firstmover** [comment]
> I've solved this on Ubuntu with version 1.5.3
> 
> 1. Delete the old *.asar
>    `sudo rm -rf ~/.config/obsidian/obsidian-1.5.3.asar`
> 2. Unzip file and copy file to the config folder. [obsidian-1.5.3.asar.zip](https://github.com/elias-sundqvist/obsidian-annotator/files/13803802/obsidian-1.5.3.asar.zip)
>    `sudo cp ~/Download/obsidian-1.5.3.asar ~/.config/obsidian/`
> 3. Then restart Obsidian

Thank you. This worked for my macOS. @BaoDoanUit

**Comment by ErikSkansberg** [comment]
+1

**Comment by ErikSkansberg** [comment]
Bit of a newb 
I tried to follow the steps provided by @RijoRoriz however when I looked into the Appdata folder I was not able to find the file obsidian-1.5.2.asar do we know if a patch to the annotator plug in will be coming out to fix this? 
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/57766298/83adc87d-088c-4d83-b486-a4e6d2b1d7d6)

**Comment by elias-sundqvist** [comment]
> Damn, I don't see how to make a quick fix for that. In my understating plugin requires complete rewrite from scratch to remove fetching resources with blob 😞

Only css blobs are blocked, so the issue is not *that* big. I just need to ensure the styling is applied some other way. I can probably release a fix this weekend.

**Comment by nepisodes** [comment]
> > I have successfully solved this problem on macOS related to Obsidian, with thanks to @WilliamsJack. The steps are as follows:
> > 
> > 1. Open the Terminal application.
> > 2. cd ~/Library/Application\ Support/obsidian/
> > 3. Open the file "obsidian-1.5.3.asar" using a text editor like vim or any other editor of your choice.
> > 4. Locate the line that contains "".
> > 5. Comment out the line by adding a comment symbol (e.g., "")
> > 6. Save the changes and close the editor.
> > 7. Restart the Obsidian application.
> 
> What is 4 step?

This worked for me:

```
.annotationLayer .highlightArea:hover::after {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  -webkit-backdrop-filter: var(--hcm-highligh-filter);
          backdrop-filter: var(--hcm-highligh-filter);
  /* content: ""; */
  pointer-events: none;
```

**Comment by aidiaware** [comment]
> > > I have successfully solved this problem on macOS related to Obsidian, with thanks to @WilliamsJack. The steps are as follows:
> > > 
> > > 1. Open the Terminal application.
> > > 2. cd ~/Library/Application\ Support/obsidian/
> > > 3. Open the file "obsidian-1.5.3.asar" using a text editor like vim or any other editor of your choice.
> > > 4. Locate the line that contains "".
> > > 5. Comment out the line by adding a comment symbol (e.g., "")
> > > 6. Save the changes and close the editor.
> > > 7. Restart the Obsidian application.
> > 
> > 
> > What is 4 step?
> 
> This worked for me:
> 
> ```
> .annotationLayer .highlightArea:hover::after {
>   position: absolute;
>   top: 0;
>   left: 0;
>   width: 100%;
>   height: 100%;
>   -webkit-backdrop-filter: var(--hcm-highligh-filter);
>           backdrop-filter: var(--hcm-highligh-filter);
>   /* content: ""; */
>   pointer-events: none;
> ```

Mmm... I have found no .asar file in /Users/.../Library/Application Support/obsidian (MacOS)
Does it make any sense?
Thanks.

**Comment by nepisodes** [comment]
> > > > I have successfully solved this problem on macOS related to Obsidian, with thanks to @WilliamsJack. The steps are as follows:
> > > > 
> > > > 1. Open the Terminal application.
> > > > 2. cd ~/Library/Application\ Support/obsidian/
> > > > 3. Open the file "obsidian-1.5.3.asar" using a text editor like vim or any other editor of your choice.
> > > > 4. Locate the line that contains "".
> > > > 5. Comment out the line by adding a comment symbol (e.g., "")
> > > > 6. Save the changes and close the editor.
> > > > 7. Restart the Obsidian application.
> > > 
> > > 
> > > What is 4 step?
> > 
> > 
> > This worked for me:
> > ```
> > .annotationLayer .highlightArea:hover::after {
> >   position: absolute;
> >   top: 0;
> >   left: 0;
> >   width: 100%;
> >   height: 100%;
> >   -webkit-backdrop-filter: var(--hcm-highligh-filter);
> >           backdrop-filter: var(--hcm-highligh-filter);
> >   /* content: ""; */
> >   pointer-events: none;
> > ```
> 
> Mmm... I have found no .asar file in /Users/.../Library/Application Support/obsidian (MacOS) Does it make any sense? Thanks.

No it doesn't...

This file `obsidian-1.5.3.asar` should be there...

**Comment by elias-sundqvist** [comment]
I have updated obsidian to version 0.2.11 with a potential fix. Is it working better for people now?

**Comment by Seraphli** [comment]
Works on Obsidian 1.5.3

**Comment by dalibord** [comment]
> I have updated obsidian to version 0.2.11 with a potential fix. Is it working better for people now?

Works fine v1.5.3, thanks

**Comment by aidiaware** [comment]
Fantastic! It is working now. Thank you so much! (obsidian 1.5.3)
