### ISSUE TITLE
Bugs in Obsidian 1.5.3

### ISSUE THREAD

**Issue by vituri** [elias-sundqvist/obsidian-annotator#357]
Hi!

The annotator plugin worked perfectly on Obsidian 1.4. After the auto-update to version 1.5.3, there is a bug in which the pages of the pdf shrink when I click anywhere.

Example:

The book opened as usual
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/56522687/6d438fb6-9bbc-49fb-9ec5-a8b02e39934f)

after clicking anywhere inside annotator:
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/56522687/45c3b189-2160-4c9d-a6a6-fbcca9ff3b40)

After clicking again, it goes back to the original size. This makes it impossible to highlight anything.

Details of the footer below:
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/56522687/8a32f7ce-b35f-4877-bead-4cd692187a93)

Another problem is that all highlighst are now black when not in dark mode:
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/56522687/9fd851ff-0802-4774-b3e0-ce32a87eb4b1)

now in dark mode:
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/56522687/7512eb7b-fbf6-4b2d-9477-6366a0c96043)

Thanks for this nice plugin!

**Comment by DM1122** [comment]
Hey, see duplicate issue: https://github.com/elias-sundqvist/obsidian-annotator/issues/356

**Comment by vituri** [comment]
Oops, sorry! I have searched the issues by the term "obsidian 1.5". Closing here to follow in the other issue.
