### ISSUE TITLE
Can not annotate, the page is scaling every time I click

### ISSUE THREAD

**Issue by Eplus22** [elias-sundqvist/obsidian-annotator#358]
![problem](https://github.com/elias-sundqvist/obsidian-annotator/assets/119471804/f07e94da-3229-4bd3-ad24-250934d0857e)

So I open the file using annotator and try to highlight some text to annotate. 

But every time I click the page, it scales and I can't use it. Any help? thanks.

Windows 11
Obsidian Version: 1.5.3
Annotator Version: 0.2.10

---update---

‼️This issue duplicates with #356, check @WilliamsJack 's [answer](https://github.com/elias-sundqvist/obsidian-annotator/issues/356#issuecomment-1872516525). it helps solve the issue. thanks :)

**Comment by nstebbins** [comment]
+1 I have the same issue

https://github.com/elias-sundqvist/obsidian-annotator/assets/5514378/94ccdc32-dc37-4ea6-943a-cfb257b43775

**Comment by alex-burton-ac** [comment]
I also am experiencing this issue.

**Comment by Supernovatux** [comment]
I am experiencing the same issue
Arch linux 6.6.8-zen1-1.1-zen
obsidian 1.5.3-1 
Annotator Version: 0.2.10
Not sure if the below log file will but anyways
[obsidian.md-1703864117992.log](https://github.com/elias-sundqvist/obsidian-annotator/files/13794570/obsidian.md-1703864117992.log)

**Comment by Please-help-me-Thanks** [comment]
I also am experiencing this issue.
My obsidian version is v1.5.3 and the Annotator version is 0.2.10

**Comment by harrystuart** [comment]
I am also experiencing this issue.

**Comment by mgmobrien** [comment]
Same issue

**Comment by sosacode20** [comment]
Same issue over here.
- Obsidian versión 1.5.3
- Annotator version is 0.2.10

**Comment by WilliamsJack** [comment]
Also noted at https://github.com/elias-sundqvist/obsidian-annotator/issues/356#issuecomment-1872516525 (duplicate issue)

 ---

It looks like this is due to a new CSP added to Obsidian's `index.html` in 1.5:

```html
<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com">
```

I haven't been able to fix the plugin directly, as it's a bit out of my area of expertise, but I did confirm the cause of the issue by unpacking `obsidian-1.5.3.asar`, removing the CSP from `index.html` and repacking it, allowing Obsidian Annotator to run on 1.5.3.

![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/30068301/1dafe69e-9aae-4c0b-b86c-0136290aff08)

**Comment by MatanRubin** [comment]
Same here. Obsidian 1.5.3, Annotator 0.2.10, on macOS.

**Comment by Mahgozar** [comment]
> Also noted at [#356 (comment)](https://github.com/elias-sundqvist/obsidian-annotator/issues/356#issuecomment-1872516525) (duplicate issue)
> 
> It looks like this is due to a new CSP added to Obsidian's `index.html` in 1.5:
> 
> ```
> <meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-inline' 'self' https://fonts.googleapis.com">
> ```
> 
> I haven't been able to fix the plugin directly, as it's a bit out of my area of expertise, but I did confirm the cause of the issue by unpacking `obsidian-1.5.3.asar`, removing the CSP from `index.html` and repacking it, allowing Obsidian Annotator to run on 1.5.3.
> 
> ![image](https://private-user-images.githubusercontent.com/30068301/293459456-1dafe69e-9aae-4c0b-b86c-0136290aff08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NjU2NzcsIm5iZiI6MTcwMzk2NTM3NywicGF0aCI6Ii8zMDA2ODMwMS8yOTM0NTk0NTYtMWRhZmU2OWUtOWFhZS00YzBiLWI4NmMtMDEzNjI5MGFmZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNGU5ZDQwYzFjMGEyYjA5ZTY3ZGNjMzM3MmFjZTljMjZlYjI1YzQyZTRjZWI4MTY0N2QwYThhYmQ4OTZhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IjKwn-zzgAdBnw6t-isNQ1cr7WaNFfoyvqT6CmZnx8)

this fix causes obsidian to ask me to turn off protected view every time on startup

**Comment by edwardmilsom** [comment]
Same issue

**Comment by wehyy** [comment]
Same issue

**Comment by Abdullah-AlAttar** [comment]
Same, happening to me on Windows11,

**Comment by ErikSkansberg** [comment]
+1

**Comment by LucavonHumboldt** [comment]
+1
