### ISSUE TITLE
Annotations panel moved under the page

### ISSUE THREAD

**Issue by Giacint1** [elias-sundqvist/obsidian-annotator#359]
The annotation panel has moved from a side position to the bottom under the main window, causing an additional scroll bar to be added.It's still functional, but it's compressed on all sides, so it's impossible to use.

Haven't used this plugin in a while and have been modifying the base a lot. It used to work fine before. Tried installing on a clean base, without other mods, the problem remained.

Please advise me what settings could affect such a change in the position of the panel and how it can be fixed. 

![0101193951_Obsidian](https://github.com/elias-sundqvist/obsidian-annotator/assets/155383352/d74067d9-3dc7-42a7-9ec5-aa0e5c088cc1)
![0101194100_Obsidian](https://github.com/elias-sundqvist/obsidian-annotator/assets/155383352/94f6be1d-ca42-4dd1-8e55-27b6e6950b56)

**Comment by Artemiy42** [comment]
Same obsidian v1.5.3, annotator v0.2.10, macOS v13.2.1

**Comment by mirsking** [comment]
+1

**Comment by yorelog** [comment]
+1

**Comment by Giacint1** [comment]
> see： [#356 (comment)](https://github.com/elias-sundqvist/obsidian-annotator/issues/356#issuecomment-1869753158)

Unfortunately, this method means rolling back to the previous version of Obsidian, which means losing all of its new features.
[elias-sundqvist](https://github.com/elias-sundqvist) announced that they are working on a new version of the plugin. I will wait for the update.
See: https://github.com/elias-sundqvist/obsidian-annotator/issues/356#issuecomment-1877888272

**Comment by Giacint1** [comment]
With the 0.2.11 update, the problem has been resolved.
**Important:** I had to uninstall and reinstall the plugin. Updating over the old version did not work.
