### ISSUE TITLE
.7 Release Interfering with Obsidian Sync

### ISSUE THREAD

**Issue by cyrulnik** [elias-sundqvist/obsidian-annotator#36]
On my installation, enabling the .7 release causes Obsidian Sync to stop working. After enabling the plugin and restarting Obsidian, files no longer sync and "version history" for all files is blank. Sync activity shows "1000 normal closure error" repeatedly -- and the same error shows up in dev console. 

Disabling this plugin and restarting Obsidian resolves all issues immediately for me.

**Comment by elias-sundqvist** [comment]
That's pretty strange. 
I saw your message on Discord also.

From your errors, it looks like the global websocket class stops working. I don't replace the websocket classes globally, as far as I'm aware. 
Maybe the mock-websocket class does more than I expected though.

**Comment by elias-sundqvist** [comment]
This should be fixed in the new version.
I haven't tested it, but I found an option in the mock-websocket class for overriding the global websocket, which I disabled. 
I would be very surprised if this wasn't the issue.
