### ISSUE TITLE
Obsidian Annotator not renderring - Updated 0.2.11

### ISSUE THREAD

**Issue by PrithiPal** [elias-sundqvist/obsidian-annotator#363]
**Problem**: Annotations doesn't appear even after updating annotator plugin to 0.2.11 following bugfix for my previous thread
https://github.com/elias-sundqvist/obsidian-annotator/issues/356

**Screenshots**
1. Empty canvas after switching to "Annotate" from three dots page options.
![Screenshot 2024-01-08 132637](https://github.com/elias-sundqvist/obsidian-annotator/assets/147000835/d87e9b36-e03e-4f20-a080-43eb78dd71dc)
enshots**

2. Obsidian and 
![Screenshot 2024-01-08 132818](https://github.com/elias-sundqvist/obsidian-annotator/assets/147000835/689bb743-3481-4fb3-b545-916d80878984)
![Screenshot 2024-01-08 132810](https://github.com/elias-sundqvist/obsidian-annotator/assets/147000835/6e0b0af8-44b1-4973-8052-7121faa535a2)

**What I tried?**
1. Reinstalled Obsidian
2. Reinstalled Annotator plugin with latest version.
3. Removed Annotator plugin manually from `.obsidian/plugins/obsidian-annoator` and manually placed release's files ( `main.json` and `manifest.json` from https://github.com/elias-sundqvist/obsidian-annotator/releases/tag/0.2.11
4. Delete `.asar` file, restarted obsidian and tried again ( obsidian creates new `.asar` file by default if not found ) 

Blob attachment warnings still appears.

**Comment by Seraphli** [comment]
Having a similar problem here.  Version 0.2.11 worked yesterday but doesn't work today. The annotator can not be opened.
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/1586755/cdd53b0e-675f-4cf7-b9f0-2ef84102c898)

**Comment by shaiyarothberg** [comment]
Hi! I'm having the same problem as https://github.com/elias-sundqvist/obsidian-annotator/issues/363#issue-2071260395 on mobile and pc: Empty canvas after switching to "Annotate" from three dots page options.
Thanks!

**Comment by PrithiPal** [comment]
The issue, seems to be resolved on my system.
![Screenshot 2024-02-19 144818](https://github.com/elias-sundqvist/obsidian-annotator/assets/22536182/37e226c8-6399-474f-a478-2bb9b12908f3)

Obsidian Version: `v1.5.6`
OS: Windows 11
Annotator Versoin: `0.2.11`

No additional steps, I installed annotator plugin, enabled it, created new notes, tied to existing pdf and toggle Annotator view. I'm closing this issue.
