### ISSUE TITLE
[Bug] Display bug in annotator view

### ISSUE THREAD

**Issue by someone-eng** [elias-sundqvist/obsidian-annotator#368]
![bug](https://github.com/elias-sundqvist/obsidian-annotator/assets/82312730/79315293-7f5c-44e4-8f1f-a1df97e107da)
My highlight now become dark and the content is covered. 

And there is something wrong with my side panel when I use annotator view, see as follows:
![image](https://github.com/elias-sundqvist/obsidian-annotator/assets/82312730/0843f8fc-0f5f-4247-ac01-d6c766384104)
Once I click anywhere of the page in annotator view, the above situation comes out.

My obsidian is v1.5.3, newest until now. I wonder if there is any bugs in the annotator plugin, or just something changed in my computer?
Thanks for any upcoming suggestions!

**Comment by prateekgargX** [comment]
I am facing the same issue on my system
Platform: Apple Silicon M2
Obsidian: v1.5.3
Annotator: v0.210

**Comment by elutac** [comment]
I was experiencing the same bug. Updating the plugin to version 0.2.11 fixed it.

**Comment by someone-eng** [comment]
> I was experiencing the same bug. Updating the plugin to version 0.2.11 fixed it.

That works, thank you very much!
