### ISSUE TITLE
Create new pdf reader by default

### ISSUE THREAD

**Issue by johans3** [elias-sundqvist/obsidian-annotator#46]
Annotator is a hilariously awesome plugin 👍👍👍 omg!

At first I felt disoriented how to launch this plugin, so I went back to read again your instructions.

Anyway, I'd prefer if Annotator would have the killer feature to create the *pdf reader window* by itself, because there's no going back to the original md file. The front matter tag gets its info from the links clicked beforehand 

So my suggestion is following:
1) we add manually a link [filename](best if remote) in a document.md file
2) we click on the link in point 1
3) Annotator creates by itself a *pdf reader window* and puts that *file.md* in a predefined "read" folder specified by the user

**Comment by 6-AND-9** [comment]
+1

**Comment by elias-sundqvist** [comment]
> @johans3 are you asking for the ability to auto create this markdown file from a PDF file? Because I'd LOVE a Ctrl+P shortcut to be able to generate that markdown file for us, but in the same directory and same name as the PDF (without .pdf) as the original file. Not sure if I should create a separate issue or not for that. Thoughts @elias-sundqvist ? Love this plugin btw.

Yeah, I will add the ability to automatically generate annotation files in the next release. I've been very busy with school recently, so I haven't had much time to work on the plugin, but I'll get to it eventually.

**Comment by johans3** [comment]
> but in the same directory and same name as the PDF

sounds reasonable and logic at first glance - 
but I keep my pdfs outside Obsidians vault, as I keep sources and tools apart. Pdfs are referenced only. 

Therefore, the MD file should be created in my vault but not in the same directory as my referenced pdf, which lies outside
