### ISSUE TITLE
Dragging highlight from PDF to another file/pane to create a link is not working

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#49]
It isn't doing anything when trying to drag a highlight into another file to create a link (new feature you just released). It just tries to drag more text around the highlight.

https://user-images.githubusercontent.com/64155612/132382197-fb03336d-6c60-4270-b9d9-6ea18641b8bd.mp4

**Comment by elias-sundqvist** [comment]
are you holding <kbd>shift</kbd>

**Comment by GitMurf** [comment]
DUH! wow... I somehow missed that requirement, haha. Sorry! Yes it works with Shift held :)
