### ISSUE TITLE
New drag and drop feature conflicting with other drag and drop Obsidian plugins

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#50]
The new drag and drop feature conflicts with my plugin I am developing that does drag and drop stuff. Additionally it also gives the same error when trying to do Obsidian native drag and drop of search results from left sidebar search view into a file/pane which creates a link to where the search result came from.

For my plugin it completely breaks it on the onDrop event. For obsidian native search result dragging it still looks like it does what it is supposed to but gives the same error. I assume you hook into the Drag event drop listener... I would first add a check to see if the drag is coming from one of your PDF annotator leafs/views and if not, abort. Otherwise it appears it is running your code on any drop event which several plugins use.

What I do to check for this is on dragstart event I set a variable that tells me it was my plugin drag handle that was started so that then on drop I know to do stuff for it. And then I always clear that variable on any drop. That way if it wasn't started by my plugin drag and drop handle then my code won't try to run. Alternatively I think you can add a custom property to the evt.dataTransfer object that handles drag and drop data.

![image](https://user-images.githubusercontent.com/64155612/132382775-30785696-0bd2-4943-9ccc-d5a6de000bf2.png)

I have to disable your plugin right now because otherwise my drag and drop plugin won't work... and the native search drag and drop appears to work but puts the error in the console each time (so everyone is effected by it, not just when using my plugin).

Let me know if you have any questions.

**Comment by GitMurf** [comment]
So it looks like this error happens when you have NOT dragged a highlight from a PDF into a file yet. So maybe there is some variable you are setting on dragStart that is checked for in the onDrop event but if a highlight hasn't been dragged yet then that variable was never set and therefore in the onDrop event it is throwing up that error? May just be you need to check for a NULL first?

Easiest way to test is to close out of obsidian, start it fresh, then try dragging a Search result into a file/pane and you will see the error in the console.

**Comment by GitMurf** [comment]
The reason that my plugin "breaks" and the obsidian core throws the error but still works is that we must be hooking to the same HTML element for our dop event? Are you hooking to `document.getElementsByClassName('workspace-split mod-vertical mod-root')`?

**Comment by GitMurf** [comment]
In looking at your code I think you would be better off registering a DOM event using the obsidian API as then when someone turns off your plugin it will remove your event listeners. As it stands, if your plugin is disabled your onDrop events are still firing. So you have to close obsidian and re-open.

Here in the API is the recommneded way of attaching DOM events. I am not sure if there is a way to do something similar straight within the codemirror event listeners... you need to ask Licat. But right now your event listeners aren't unloading when your plugin is turned off: https://github.com/obsidianmd/obsidian-api/blob/bde556afa033e909ebfb9fcee8f5ef288276f78f/obsidian.d.ts#L518

Also it looks like you are doing a preventDefault. I'm not sure if this is what is killing my plugin drag and drop or not but I'm not sure this is a good idea as it may be stopping any plugins that use drag and drop. We can test it once you apply some fixes and see if my plugin works again.

![image](https://user-images.githubusercontent.com/64155612/132386030-7fc340dd-cce0-46c2-a415-226d1504a1e9.png)

**Comment by elias-sundqvist** [comment]
I've released a new version of the plugin now which has _hopefully_ fixed the issue. I'm kind of surprised that the `this.dragData !== null` check wasn't sufficient though.

**Comment by GitMurf** [comment]
I can confirm it seems to be working as expected! Thanks!
