### ISSUE TITLE
Allow for YAML annotation-target key:value to have target in array "format"

### ISSUE THREAD

**Issue by GitMurf** [elias-sundqvist/obsidian-annotator#51]
Many people use the popular MetaEdit plugin where it adds meta data to your YAML frontmatter quickly and you can templatize things. But it adds it into an array format in case you want to give a property multiple values. It appears that the Annotator plugin will not read the path if you have it like `annotation-target: [my-pdf-name.pdf]`. Could you update to read it in this format as well?

```
---
annotation-target: [Unattended_Brief.pdf]
---
```

**Comment by elias-sundqvist** [comment]
This should be resolved in the new release :)

**Comment by GitMurf** [comment]
I can confirm this is resolved. Thanks!
