### ISSUE TITLE
Is there any way to open the block reference in a new pane?

### ISSUE THREAD

**Issue by link-ding** [elias-sundqvist/obsidian-annotator#54]
I want to open the block reference in a new pane, I tried the cmd + click the link and right click the link, but both of them will open the PDF highlight in current pane

**Comment by GitMurf** [comment]
Thank you for posting this!! I thought it was just me who couldn't figure it out! I would like this very much as well.

**Comment by elias-sundqvist** [comment]
<kbd>ctrl</kbd>or <kbd>cmd</kbd> clicking (or alternatively, clicking with the mouse wheel) to open annotations in a new pane has now been added in the new release (0.1.1).

**Comment by kata-owl** [comment]
does this work on edit mode?, I tried both ctrl + click and mouse wheel click in edit mode and both of them opened the PDF highlight in current pane.
