### ISSUE TITLE
Epub load failed

### ISSUE THREAD

**Issue by 820239854** [elias-sundqvist/obsidian-annotator#6]
![image](https://user-images.githubusercontent.com/25190645/131113819-eff67e1f-d4fd-455f-ac1d-3af44d8961a0.png)

![image](https://user-images.githubusercontent.com/25190645/131113858-44d2ab83-e56c-488f-ac35-bf80f34e72ad.png)

![image](https://user-images.githubusercontent.com/25190645/131113892-d4072ef5-fabc-4f90-bb07-e3075aff839e.png)

**Comment by 820239854** [comment]
Thank you! may be you could try another PC to test it.

This problem occurs to me twice,

**Comment by elias-sundqvist** [comment]
Thanks for reporting the issue! I think I've solved it now. 
Apparently some of the needed files were `.gitignore`d before, (there is a folder called `node_modules` which should be included in the bundle.)

**Comment by 820239854** [comment]
Yeah,Thank you very much! It works great
