### ISSUE TITLE
bug: Option "annotate" does not appear.

### ISSUE THREAD

**Issue by TobiasKlosek** [elias-sundqvist/obsidian-annotator#60]
Hello!

Im trying to use this plugin and did everything like in the example:

Creating a new note -> insert "annotation-target:: https://arxiv.org/pdf/2104.13478.pdf" and clicked on the three dots.
But the "annotate"-Option dont appears.

Im running Obsidian 12.15 and the Plugin Version 0.1.1

**Comment by elias-sundqvist** [comment]
Is this the same issue as #42?

**Comment by TobiasKlosek** [comment]
Thanks! Installing Dataview solved that!
