### ISSUE TITLE
Obsidian Annotator v0.1.1 seems to be invalid.

### ISSUE THREAD

**Issue by loveshizuka** [elias-sundqvist/obsidian-annotator#61]
Obsidian Annotator v0.1.1 seems to be invalid. It can not take the annotations of PDF to "Open as MD". If downgrade to version 0.1.0, everything is OK.

Obsidian: v0.12.15
Obsidian Annotator: v0.1.1
System: Win10 21H1

**Comment by elias-sundqvist** [comment]
Could you take some screenshots to illustrate the problem? Everything seems to work for me.

**Comment by loveshizuka** [comment]
Annotator v0.1.1:
https://user-images.githubusercontent.com/25612355/132950544-9973ab8b-5393-40e4-939e-1ac455881e26.mp4

Annotator v0.1.0:
https://user-images.githubusercontent.com/25612355/132950571-8851278f-a365-486e-b8bf-67c5a2fb6559.mp4

The test is performed in a newly installed environment, and only the Annotator plug-in is installed. I don’t know if it’s because of a mistake in my operation.

**Comment by elias-sundqvist** [comment]
Ok I see the issue. I'll try to replicate and fix it later today.

**Comment by elias-sundqvist** [comment]
I released a new version now (0.1.2) which should fix the issue.
I've also added some tests to make issues like this less likely in the future. 
If you have any suggestions for how I could make my releases more reliable, feel free to write a comment in issue  #58
