### ISSUE TITLE
Can not find the annotation option in the more option(3 vertical dots)

### ISSUE THREAD

**Issue by tom-00** [elias-sundqvist/obsidian-annotator#63]
So, I did exactly as the doc says;  annotation-target:: pdf location in the vault (or annotation-target-pdf:: pdf location in the vault) still cant find any annotation option.

**Comment by elias-sundqvist** [comment]
duplicate of #42?

**Comment by tom-00** [comment]
Thanks

**Comment by tom-00** [comment]
Got the annotate option but showing a missing pdf file. I have tried with several pdf files (stored in the vault) . But still showing missing pdf file.

**Comment by tom-00** [comment]
Error message: 

PDF.js v2.3.160 (build: b2856b16)
Message: Missing PDF "https://via.hypothes.is/proxy/static/xP1ZVAo-CVhW7kwNneW_oQ/1628964000/vault://home/zois/Dropbox/Research%20/paper/2019.pdf".

**Comment by elias-sundqvist** [comment]
No, everything should work offline. Maybe you could send a screenshot or something to illustrate the problem?

**Comment by tom-00** [comment]
![annotation ](https://user-images.githubusercontent.com/90553626/133018363-1f846990-16ce-4e2e-9425-d05d46cbf93f.png)

**Comment by tom-00** [comment]
It is happening for every single pdf

**Comment by tom-00** [comment]
Thanks bro, its working... and Tnx for the plugins... This single plugin can change the fate of many pdf readers. Best wishes.

**Comment by elias-sundqvist** [comment]
Thanks :)
