### ISSUE TITLE
the annotation item does not appear in the context menu three dots

### ISSUE THREAD

**Issue by Quadkiev** [elias-sundqvist/obsidian-annotator#66]
Hey! My dream is to use your masterpiece. After installing the plugin, the context menu does not appear?
annotator V0.1.3. obsidian V0.12.15

https://user-images.githubusercontent.com/11949890/133630886-d4b31827-f30e-4d0b-8b01-b1a502f12415.mov

**Comment by elias-sundqvist** [comment]
try writing 
```
---
annotation-target: 222.pdf
---
```

**Comment by Quadkiev** [comment]
sorry

**Comment by elias-sundqvist** [comment]
No worries :)
