### ISSUE TITLE
Cannot get option annotate after adding PDF

### ISSUE THREAD

**Issue by migdur** [elias-sundqvist/obsidian-annotator#67]
Hi there,

i am using Obsidian 0.12.15 and just installed this annotation plugin (brand new Vault, only this community plgin installed). I am following the documented instructions (add annotation-target:: path/to/a/pdf) but I don't seem to be able to get the option 'Annotate' showing up in the 'More options' menu. Am I actually missing anything? Thanks for clarifying.

**Comment by elias-sundqvist** [comment]
duplicate of #42?

**Comment by migdur** [comment]
Yep, seems to be the same problem. Thanks.
