### ISSUE TITLE
Annotations created on iPad are not visible on Windows and Android. 

### ISSUE THREAD

**Issue by zsviczian** [elias-sundqvist/obsidian-annotator#70]
This is an awesome plugin! Thank you!

I use Obsidian sync.
I started annotating a document on Windows and wanted to continue on my iPad. Annotations created on my PC weren't visible on the iPad, but were visible on my other PCs and also on my Android phone. In Markdown view, I could see my "PC" annotations on the iPad as well, and when I added annotations to the same document on the iPad, those were also added to the markdown view, visible in markdown on the PC, but not in the Annotation view. In short, the files were synching correctly, and the markdown file seemed intact.

I think I found the cause. It has to do with how space in the filename is handled in the JSON in these fields: `source:`, `uri:`, `href:`. On the iPad filenames are encoded (i.e. space == %20) on the PC and on my Android the filenames do not seem to get encoded. When I replaced %20 with a space the annotations created on the iPad appeared in the annotation view on the PC, but disappeared on the iPad.

**Comment by jonasmerlin** [comment]
Me too! Has anyone found any workarounds for this yet?

**Comment by zsviczian** [comment]
> Me too! Has anyone found any workarounds for this yet?

The workaround is simple - as described in the issue above. Make sure that the file path including the filename of the annotation file does not contain space characters. Then it works.

**Comment by jonasmerlin** [comment]
> > Me too! Has anyone found any workarounds for this yet?
> 
> The workaround is simple - as described in the issue above. Make sure that the file path including the filename of the annotation file does not contain space characters. Then it works.

Thanks for the reply, but since that's not an option for me I decided to fix this in this PR #94 

Until that's merged you could theoretically used a built version of my forked repo to fix this in the meantime, but I guess I would not recommend that, as it's a bit of a hassle.
