### ISSUE TITLE
changing font size in the epub reader

### ISSUE THREAD

**Issue by pastorjack** [elias-sundqvist/obsidian-annotator#72]
Hello,
I have poor eyesight so I need to be able to increase the font size in the epub reader. Is this currently possible?
Thank you!

**Comment by elias-sundqvist** [comment]
I don't think it's possible right now... 

I will add it to the todo list.

**Comment by pastorjack** [comment]
I greatly appreciate it!

**Comment by mikhasev** [comment]
Yep! This would be great! And to be able to reformat it to remove all the whitespace around the book text

**Comment by mdziadowiec** [comment]
+1

**Comment by aladmit** [comment]
The latest release has font size settings for epub reader. It's a little glitchy, but works most of the time :)
