### ISSUE TITLE
Unable to load a small pdf present in the vault

### ISSUE THREAD

**Issue by psychsatani** [elias-sundqvist/obsidian-annotator#8]
Not sure how to describe what is happening. I have added a video. 

https://user-images.githubusercontent.com/78266798/131232204-8ec7606d-0ff2-4ac5-b5cb-b4881cdecff9.mov

**Comment by shawngraham** [comment]
I get the same error; when I check the developer console, I see this:
![Screen Shot 2021-08-29 at 12 23 15 PM](https://user-images.githubusercontent.com/4266026/131257779-0a1e43ff-7b01-4cbd-a5fd-ffed68bf26a9.png)

cross-origin block?

**Comment by elias-sundqvist** [comment]
Looks like the iframe override has some issues for you, so you see the actual hypothes.is site instead of the patched version. The same thing probably happens in issue  #9. 

I'll try to reproduce and hopefully fix the issue next week.

**Comment by elias-sundqvist** [comment]
What happens in the latest release? Does it work now?

**Comment by shawngraham** [comment]
It does! Thank you.
