### ISSUE TITLE
Can't open epub file on android

### ISSUE THREAD

**Issue by Yyote** [elias-sundqvist/obsidian-annotator#83]
Epub files don't open on android. Instead it shows me this:
![Screenshot_2021-11-14-19-22-38-549_md obsidian](https://user-images.githubusercontent.com/94308727/141689441-ea49e414-4368-498a-9f65-8b4e40eda0bc.jpg)

Everything is ok on Windows.

**Comment by elias-sundqvist** [comment]
Duplicate of #1
