### ISSUE TITLE
OBSIDIAN0.13.2 version，hold Shift and drag the PDF highlight section, will display this string of characters: drag-event::hypothesis-highlight.

### ISSUE THREAD

**Issue by MILKMILKKING** [elias-sundqvist/obsidian-annotator#86]
OBSIDIAN0.13.2 version, the introduction of Experimental Live Preview function, but since the upgrade, hold Shift and drag the PDF highlight section, will display this string of characters: drag-event::hypothesis-highlight.

**Comment by saeneas** [comment]
Same here on windows 11 and 13.19

**Comment by Kiritor729** [comment]
Same here on windows 11 and 15.9

**Comment by Wcdaren** [comment]
me too
![image](https://user-images.githubusercontent.com/25494875/219855476-a03cc1f3-21fe-4003-8ad7-75db93c14587.png)
![image](https://user-images.githubusercontent.com/25494875/219855482-4f4405e9-f7e5-4606-aa72-6edcf0e1169f.png)

**Comment by whvids123** [comment]
It is still never solved until now, on win11,v1.5.3,and annotator 0.2.11
