### ISSUE TITLE
Annotations lost after update

### ISSUE THREAD

**Issue by HansiMeier** [elias-sundqvist/obsidian-annotator#95]
Great plugin! I really like and enjoy it very much. Reading notes land automatically in Obsidian. Though after the last update the annotations and highlights in the pdf view are not shown anymore. Before the update everything was working fine. In markdown view the data are still there. When I enter something new the new information doesn't appear anywhere. I am working on Samsung Tablet S4 with Android and all software versions with latest updates. Any suggestions? Do you need more information?

By the way, epub files didn't work before and don't work now.

Please  maike me happy again;-)

[📚 Reiner Keller÷Diskursforschung Annotation 1.md](https://github.com/elias-sundqvist/obsidian-annotator/files/7741359/Reiner.Keller.Diskursforschung.Annotation.1.md)

**Comment by elias-sundqvist** [comment]
Thanks. I'll try to fix it asap

**Comment by elias-sundqvist** [comment]
I tried guessing what the error was and pushed a quick fix now. If this doesn't fix the issue. It would be great if you could also provide the pdf so that I can try opening it.

**Comment by HansiMeier** [comment]
Wow, that was fast. Or quick. Anyway  😆. I'll check and report. Thank you anyway.

**Comment by HansiMeier** [comment]
It seems you guessed very well, my dear fellow. The annotations are just back after a new update via the store. I'll go on to read and annotate. If I find s.th., I'll tell you. For the first look everything looks just great. Thanx a lot.

**Comment by HansiMeier** [comment]
Oh, sorry! I nearly forgot the pdf. Here it comes! It's in the same folder as the annotation file: /Lesetexte/pdf . Be free to ask for more information! Enjoy to support the maker of this great plugin.
[Reiner Keller÷Diskursforschung.pdf](https://github.com/elias-sundqvist/obsidian-annotator/files/7741635/Reiner.Keller.Diskursforschung.pdf)
