### ISSUE TITLE
Change Sentry configuration

### ISSUE THREAD

**Issue by robertknight** [elias-sundqvist/obsidian-annotator#97]
Hello,

We (Hypothesis developers) have received some Hypothesis crash reports coming from this plugin. If you want to receive them you'll need to register a Sentry account and change the `dsn` value under the `sentry` key in the `app.html` file. If you are not interested in receiving Sentry reports for the copy of Hypothesis in this plugin, I suggest to delete the `sentry` key from the settings in `app.html`.

We have enabled a filter for our crash reports so that we only receive ones from the official client going forwards.

Example of a received report:

<img width="968" alt="Obsidian sentry report" src="https://user-images.githubusercontent.com/2458/146909159-a2ba9492-4f1e-44b4-8798-06190c2926cd.png">

**Comment by elias-sundqvist** [comment]
Ok, I'll make that change soon.
Sorry for the trouble.

**Comment by robertknight** [comment]
Thanks @elias-sundqvist, and congratulations on finding a cool use for Hypothesis. For our part, it would help if we provided some pointers on creating a custom backend for the client and configuring the frontend to use it.

**Comment by robertknight** [comment]
Hello @elias-sundqvist - Would you mind taking a look at this please. The minimum change here would be to remove the `sentry` keys from the JSON configuration in https://github.com/elias-sundqvist/obsidian-annotator/blob/master/resources/hypothes.is/app.html and https://github.com/elias-sundqvist/obsidian-annotator/blob/master/resources/hypothes.is/notebook.html.

Unfortunately Sentry does not make it easy for us to filter out these errors on the server side because of the way that Electron makes HTTP requests (it doesn't set an `Origin` header).

**Comment by elias-sundqvist** [comment]
Oh, I removed it, but then managed to add it back when upgrading hypothes.is version. I'll remove it again and push an update this afternoon.

**Comment by elias-sundqvist** [comment]
I've removed the dsn from both app.html and notebook.html now. You should hopefully stop receiving crash reports as soon as people have upgraded.

**Comment by robertknight** [comment]
Thanks @elias-sundqvist! In future I think it will make sense for us to provide a way to build `app.html` and `notebook.html` files in the Hypothesis client repo, so you don't have to copy and edit the one from https://hypothes.is/app.html.
